; Mavuika

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideMavuikaHairPosition]
hash = 039618b0
vb0 = ResourceMavuikaHairPosition
$active = 1

[TextureOverrideMavuikaHairBlend]
hash = 64424fcd
handling = skip
vb1 = ResourceMavuikaHairBlend
draw = 3939, 0

[TextureOverrideMavuikaHairTexcoord]
hash = 8403fb71
vb1 = ResourceMavuikaHairTexcoord

[TextureOverrideMavuikaHairVertexLimitRaise]
hash = 890ec94f
override_vertex_count = 3939
override_byte_stride = 40

[TextureOverrideMavuikaBodyPosition]
hash = 80b13a2f
vb0 = ResourceMavuikaBodyPosition
$active = 1

[TextureOverrideMavuikaBodyBlend]
hash = 00088f8d
handling = skip
vb1 = ResourceMavuikaBodyBlend
draw = 25830, 0

[TextureOverrideMavuikaBodyTexcoord]
hash = 3af262c1
vb1 = ResourceMavuikaBodyTexcoord

[TextureOverrideMavuikaBodyVertexLimitRaise]
hash = 00323c91
override_vertex_count = 25830
override_byte_stride = 40

[TextureOverrideMavuikaHairIB]
hash = f6c93dd3
handling = skip

[TextureOverrideMavuikaHairHead]
hash = f6c93dd3
match_first_index = 0
ib = ResourceMavuikaHairHeadIB
ps-t0 = ResourceMavuikaHairHeadNormalMap
ps-t1 = ResourceMavuikaHairHeadDiffuse
ps-t2 = ResourceMavuikaHairHeadLightMap
run = CommandList\global\ORFix\ORFix
; MavuikaHairHead-vb0=039618b0.txt.001 (3939)
drawindexed = 15108, 0, 0

[TextureOverrideMavuikaBodyIB]
hash = 43f8af29
handling = skip

[TextureOverrideMavuikaBodyHead]
hash = 43f8af29
match_first_index = 0
ib = ResourceMavuikaBodyHeadIB
ps-t0 = ResourceMavuikaBodyHeadNormalMap
ps-t1 = ResourceMavuikaBodyHeadDiffuse
ps-t2 = ResourceMavuikaBodyHeadLightMap
run = CommandList\global\ORFix\ORFix
; MavuikaBodyHead-vb0=80b13a2f.txt.001 (816)
drawindexed = 1908, 0, 0

[TextureOverrideMavuikaBodyBody]
hash = 43f8af29
match_first_index = 16914
ib = ResourceMavuikaBodyBodyIB
ps-t0 = ResourceMavuikaBodyBodyNormalMap
ps-t1 = ResourceMavuikaBodyBodyDiffuse
ps-t2 = ResourceMavuikaBodyBodyLightMap
run = CommandList\global\ORFix\ORFix
; MavuikaBodyBody-vb0=80b13a2f.txt.003 (9982)
drawindexed = 48669, 0, 0

[TextureOverrideMavuikaBodyDress]
hash = 43f8af29
match_first_index = 42618
ib = ResourceMavuikaBodyDressIB
ps-t0 = ResourceMavuikaBodyDressNormalMap
ps-t1 = ResourceMavuikaBodyDressDiffuse
ps-t2 = ResourceMavuikaBodyDressLightMap
run = CommandList\global\ORFix\ORFix
; MavuikaBodyDress-vb0=80b13a2f.txt (15032)
drawindexed = 47445, 0, 0


; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active > 0
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 1
endif

; Resources -------------------------

[ResourceMavuikaHairPosition]
type = Buffer
stride = 40
filename = MavuikaHairPosition.buf

[ResourceMavuikaHairBlend]
type = Buffer
stride = 32
filename = MavuikaHairBlend.buf

[ResourceMavuikaHairTexcoord]
type = Buffer
stride = 12
filename = MavuikaHairTexcoord.buf

[ResourceMavuikaHairHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MavuikaHairHead.ib

[ResourceMavuikaBodyPosition]
type = Buffer
stride = 40
filename = MavuikaBodyPosition.buf

[ResourceMavuikaBodyBlend]
type = Buffer
stride = 32
filename = MavuikaBodyBlend.buf

[ResourceMavuikaBodyTexcoord]
type = Buffer
stride = 12
filename = MavuikaBodyTexcoord.buf

[ResourceMavuikaBodyHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MavuikaBodyHead.ib

[ResourceMavuikaBodyBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MavuikaBodyBody.ib

[ResourceMavuikaBodyDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MavuikaBodyDress.ib

[ResourceMavuikaHairHeadNormalMap]
filename = MavuikaHairHeadNormalMap.dds

[ResourceMavuikaHairHeadDiffuse]
filename = MavuikaHairHeadDiffuse.dds

[ResourceMavuikaHairHeadLightMap]
filename = MavuikaHairHeadLightMap.dds

[ResourceMavuikaBodyHeadNormalMap]
filename = MavuikaBodyHeadNormalMap.dds

[ResourceMavuikaBodyHeadDiffuse]
filename = MavuikaBodyHeadDiffuse.dds

[ResourceMavuikaBodyHeadLightMap]
filename = MavuikaBodyHeadLightMap.dds

[ResourceMavuikaBodyBodyNormalMap]
filename = MavuikaBodyBodyNormalMap.dds

[ResourceMavuikaBodyBodyDiffuse]
filename = MavuikaBodyBodyDiffuse.dds

[ResourceMavuikaBodyBodyLightMap]
filename = MavuikaBodyBodyLightMap.dds

[ResourceMavuikaBodyDressNormalMap]
filename = MavuikaBodyDressNormalMap.dds

[ResourceMavuikaBodyDressDiffuse]
filename = MavuikaBodyDressDiffuse.dds

[ResourceMavuikaBodyDressLightMap]
filename = MavuikaBodyDressLightMap.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by ~ToXiC~"

; .ini generated by XXMI (XX-Model-Importer) v1.5.8
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues
