; Varesa

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideVaresaPosition]
hash = 9784dbe3
vb0 = ResourceVaresaPosition

[TextureOverrideVaresaBlend]
hash = ef26783e
vb1 = ResourceVaresaBlend
handling = skip
draw = 27791,0 

[TextureOverrideVaresaTexcoord]
hash = 0fa7f23f
vb1 = ResourceVaresaTexcoord

[TextureOverrideVaresaVertexLimitRaise]
hash = 8872531c

[TextureOverrideVaresaIB]
hash = 488fceb4
handling = skip
drawindexed = auto

[TextureOverrideVaresaHead]
hash = 488fceb4
match_first_index = 0
ib = ResourceVaresaHeadIB
ps-t0 = ResourceVaresaHeadNormalMap
ps-t1 = ResourceVaresaHeadDiffuse
ps-t2 = ResourceVaresaHeadLightMap
run = CommandList\global\ORFix\ORFix
ps-t5 = ResourceIansanNatlanFX

[TextureOverrideVaresaBody]
hash = 488fceb4
match_first_index = 40554
ib = ResourceVaresaBodyIB
ps-t0 = ResourceVaresaBodyNormalMap
ps-t1 = ResourceVaresaBodyDiffuse
ps-t2 = ResourceVaresaBodyLightMap
run = CommandList\global\ORFix\ORFix
ps-t5 = ResourceIansanNatlanFX

[TextureOverrideVaresaFaceHeadDiffuse]
hash = 9a534567
ps-t0 = ResourceVaresaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceVaresaPosition]
type = Buffer
stride = 40
filename = VaresaPosition.buf

[ResourceVaresaBlend]
type = Buffer
stride = 32
filename = VaresaBlend.buf

[ResourceVaresaTexcoord]
type = Buffer
stride = 12
filename = VaresaTexcoord.buf

[ResourceVaresaHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = VaresaHead.ib

[ResourceVaresaBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = VaresaBody.ib

[ResourceVaresaHeadNormalMap]
filename = VaresaHeadNormalMap.dds

[ResourceVaresaHeadDiffuse]
filename = VaresaHeadDiffuse.dds

[ResourceVaresaHeadLightMap]
filename = VaresaHeadLightMap.dds

[ResourceVaresaBodyNormalMap]
filename = VaresaBodyNormalMap.dds

[ResourceVaresaBodyDiffuse]
filename = VaresaBodyDiffuse.dds

[ResourceVaresaBodyLightMap]
filename = VaresaBodyLightMap.dds

[ResourceVaresaFaceHeadDiffuse]
filename = VaresaFaceHeadDiffuse.dds


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord