namespace = Gorou

; Constants ---------------------------

[Constants]
global persist $packvar = 0
global $active = 0
global $creditinfo = 0

[KeyPack]
condition = $active == 1
Key = ]
Back = [
type = cycle
$packvar = 0,1,2
run = CommandListGorouPack

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides ---------------------------

[TextureOverrideGorouPosition]
hash = 3ce94cac
if $packvar == 0
	run = commandlist\gorou\pack0\gorouposition
elif $packvar == 1
	run = commandlist\gorou\pack1\gorouposition
elif $packvar == 2
	run = commandlist\gorou\pack2\gorouposition
endif
$active = 1

[TextureOverrideGorouBlend]
hash = f4db799d
if $packvar == 0
	run = commandlist\gorou\pack0\goroublend
elif $packvar == 1
	run = commandlist\gorou\pack1\goroublend
elif $packvar == 2
	run = commandlist\gorou\pack2\goroublend
endif

[TextureOverrideGorouTexcoord]
hash = a144269e
if $packvar == 0
	run = commandlist\gorou\pack0\goroutexcoord
elif $packvar == 1
	run = commandlist\gorou\pack1\goroutexcoord
elif $packvar == 2
	run = commandlist\gorou\pack2\goroutexcoord
endif

[TextureOverrideGorouVertexLimitRaise]
hash = 955b7007
if $packvar == 0
	run = commandlist\gorou\pack0\gorouvertexlimitraise
elif $packvar == 1
	run = commandlist\gorou\pack1\gorouvertexlimitraise
elif $packvar == 2
	run = commandlist\gorou\pack2\gorouvertexlimitraise
endif

[TextureOverrideGorouIB]
hash = b2e57c84
if $packvar == 0
	run = commandlist\gorou\pack0\gorouib
elif $packvar == 1
	run = commandlist\gorou\pack1\gorouib
elif $packvar == 2
	run = commandlist\gorou\pack2\gorouib
endif

[TextureOverrideGorouHead]
hash = b2e57c84
match_first_index = 0
if $packvar == 0
	run = commandlist\gorou\pack0\gorouhead
elif $packvar == 1
	run = commandlist\gorou\pack1\gorouhead
elif $packvar == 2
	run = commandlist\gorou\pack2\gorouhead
endif

[TextureOverrideGorouBody]
hash = b2e57c84
match_first_index = 8022
if $packvar == 0
	run = commandlist\gorou\pack0\goroubody
elif $packvar == 1
	run = commandlist\gorou\pack1\goroubody
elif $packvar == 2
	run = commandlist\gorou\pack2\goroubody
endif

[TextureOverrideGorouFaceHeadDiffuse]
hash = 5ee8444a
if $packvar == 0
	run = commandlist\gorou\pack0\goroufaceheaddiffuse
elif $packvar == 1
	run = commandlist\gorou\pack1\goroufaceheaddiffuse
elif $packvar == 2
	run = commandlist\gorou\pack2\goroufaceheaddiffuse
endif

; CommandList -------------------------

[CommandListGorouPack]
if $packvar == 0
	post Resource\ShaderFixes\help.ini\Notification = ResourceGorouPack.0
elif $packvar == 1
	post Resource\ShaderFixes\help.ini\Notification = ResourceGorouPack.1
elif $packvar == 2
	post Resource\ShaderFixes\help.ini\Notification = ResourceGorouPack.2
endif
post run = CustomShader\ShaderFixes\help.ini\FormatText
post $\ShaderFixes\help.ini\notification_timeout = time + 5.0

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 1
endif

; Resources ---------------------------

[ResourceGorouPack.0]
type = Buffer
data = "POSITION 2"

[ResourceGorouPack.1]
type = Buffer
data = "HAND ON ASS"

[ResourceGorouPack.2]
type = Buffer
data = "HANDSFREE"

[ResourceCreditInfo]
type = Buffer
data = "Created mod by tedom"

; .ini generated by Discord Bot GI_Pack
