; Escoffier

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideEscoffierPosition]
hash = 1569d000
vb0 = ResourceEscoffierPosition
$active = 1

[TextureOverrideEscoffierBlend]
hash = 47280c51
vb1 = ResourceEscoffierBlend
handling = skip
draw = 31576,0 

[TextureOverrideEscoffierTexcoord]
hash = 9798ab34
vb1 = ResourceEscoffierTexcoord

[TextureOverrideEscoffierVertexLimitRaise]
hash = 1844db3b
; override_vertex_count = 0
; override_byte_stride = 84

[TextureOverrideEscoffierIB]
hash = 7ad7e69e
handling = skip
drawindexed = auto

[TextureOverrideEscoffierHead]
hash = 7ad7e69e
match_first_index = 0
ib = ResourceEscoffierHeadIB
ps-t0 = ResourceEscoffierHeadDiffuse
ps-t1 = ResourceEscoffierHeadLightMap
ps-t2 = ResourceEscoffierHeadShadow
run = CommandList\global\ORFix\ORFix

[TextureOverrideEscoffierBody]
hash = 7ad7e69e
match_first_index = 59307
ib = ResourceEscoffierBodyIB
ps-t0 = ResourceEscoffierBodyDiffuse
ps-t1 = ResourceEscoffierBodyLightMap
ps-t2 = ResourceEscoffierBodyShadow
run = CommandList\global\ORFix\ORFix

[TextureOverrideEscoffierDress]
hash = 7ad7e69e
match_first_index = 69753
ib = null
ps-t0 = ResourceEscoffierDressDiffuse
ps-t1 = ResourceEscoffierDressLightMap
ps-t2 = ResourceEscoffierDressShadow
run = CommandList\global\ORFix\ORFix

[TextureOverrideEscoffierExtra]
hash = 7ad7e69e
match_first_index = 87798
ib = null
ps-t0 = ResourceEscoffierExtraDiffuse
ps-t1 = ResourceEscoffierExtraLightMap
run = CommandList\global\ORFix\ORFix

; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
    pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
    pre run = CustomShader\ShaderFixes\help.ini\FormatText
    pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
    $creditinfo = 1
endif

; Resources -------------------------

[ResourceEscoffierPosition]
type = Buffer
stride = 40
filename = EscoffierPosition.buf

[ResourceEscoffierBlend]
type = Buffer
stride = 32
filename = EscoffierBlend.buf

[ResourceEscoffierTexcoord]
type = Buffer
stride = 12
filename = EscoffierTexcoord.buf

[ResourceEscoffierHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = EscoffierHead.ib

[ResourceEscoffierBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = EscoffierBody.ib

[ResourceEscoffierDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = EscoffierDress.ib

[ResourceEscoffierExtraIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = EscoffierExtra.ib

[ResourceEscoffierHeadDiffuse]
filename = EscoffierHeadDiffuse.dds

[ResourceEscoffierHeadLightMap]
filename = EscoffierHeadLightMap.dds

[ResourceEscoffierHeadShadow]
filename = EscoffierHeadShadow.dds

[ResourceEscoffierBodyDiffuse]
filename = EscoffierBodyDiffuse.dds

[ResourceEscoffierBodyLightMap]
filename = EscoffierBodyLightMap.dds

[ResourceEscoffierBodyShadow]
filename = EscoffierBodyShadow.dds

[ResourceEscoffierDressDiffuse]
filename = EscoffierDressDiffuse.dds

[ResourceEscoffierDressLightMap]
filename = EscoffierDressLightMap.dds

[ResourceEscoffierDressShadow]
filename = EscoffierDressShadow.dds

[ResourceEscoffierExtraDiffuse]
filename = EscoffierExtraDiffuse.dds

[ResourceEscoffierExtraLightMap]
filename = EscoffierExtraLightMap.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by yzx"

; .ini generated by XXMI (XX-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues