namespace = Itto

; Constants ---------------------------

[Constants]
global persist $packvar = 0
global $active = 0
global $creditinfo = 0

[KeyPack]
condition = $active == 1
Key = ]
Back = [
type = cycle
$packvar = 0,1,2
run = CommandListIttoPack

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides ---------------------------

[TextureOverrideIttoPosition]
hash = 3e61a41f
if $packvar == 0
	run = commandlist\itto\pack0\ittoposition
elif $packvar == 1
	run = commandlist\itto\pack1\ittoposition
elif $packvar == 2
	run = commandlist\itto\pack2\ittoposition
endif
$active = 1

[TextureOverrideIttoBlend]
hash = f186e87b
if $packvar == 0
	run = commandlist\itto\pack0\ittoblend
elif $packvar == 1
	run = commandlist\itto\pack1\ittoblend
elif $packvar == 2
	run = commandlist\itto\pack2\ittoblend
endif

[TextureOverrideIttoTexcoord]
hash = 5bcab405
if $packvar == 0
	run = commandlist\itto\pack0\ittotexcoord
elif $packvar == 1
	run = commandlist\itto\pack1\ittotexcoord
elif $packvar == 2
	run = commandlist\itto\pack2\ittotexcoord
endif

[TextureOverrideIttoVertexLimitRaise]
hash = 57a9ae8b

[TextureOverrideIttoIB]
hash = be597118
if $packvar == 0
	run = commandlist\itto\pack0\ittoib
elif $packvar == 1
	run = commandlist\itto\pack1\ittoib
elif $packvar == 2
	run = commandlist\itto\pack2\ittoib
endif

[TextureOverrideIttoHead]
hash = be597118
match_first_index = 0
if $packvar == 0
	run = commandlist\itto\pack0\ittohead
elif $packvar == 1
	run = commandlist\itto\pack1\ittohead
elif $packvar == 2
	run = commandlist\itto\pack2\ittohead
endif

[TextureOverrideIttoBody]
hash = be597118
match_first_index = 26520
if $packvar == 0
	run = commandlist\itto\pack0\ittobody
elif $packvar == 1
	run = commandlist\itto\pack1\ittobody
elif $packvar == 2
	run = commandlist\itto\pack2\ittobody
endif

[TextureOverrideIttoFaceHeadDiffuse]
hash = 415af5cd
if $packvar == 0
	run = commandlist\itto\pack0\ittofaceheaddiffuse
elif $packvar == 1
	run = commandlist\itto\pack1\ittofaceheaddiffuse
elif $packvar == 2
	run = commandlist\itto\pack2\ittofaceheaddiffuse
endif

; CommandList -------------------------

[CommandListIttoPack]
if $packvar == 0
	post Resource\ShaderFixes\help.ini\Notification = ResourceIttoPack.0
elif $packvar == 1
	post Resource\ShaderFixes\help.ini\Notification = ResourceIttoPack.1
elif $packvar == 2
	post Resource\ShaderFixes\help.ini\Notification = ResourceIttoPack.2
endif
post run = CustomShader\ShaderFixes\help.ini\FormatText
post $\ShaderFixes\help.ini\notification_timeout = time + 5.0

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 1
endif

; Resources ---------------------------

[ResourceIttoPack.0]
type = Buffer
data = "ITTO X SJINOBU POSITION 2"

[ResourceIttoPack.1]
type = Buffer
data = "ITTO X SHINOBU HANDS FREE"

[ResourceIttoPack.2]
type = Buffer
data = "ITTO X SHINOBU HANDS ON ASS"

[ResourceCreditInfo]
type = Buffer
data = "Created mod by tedom"

; .ini generated by Discord Bot GI_Pack
