; Gorou

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideGorouPosition]
hash = 3ce94cac
vb0 = ResourceGorouPosition

[TextureOverrideGorouBlend]
hash = f4db799d
vb1 = ResourceGorouBlend
handling = skip
draw = 29967,0 

[TextureOverrideGorouTexcoord]
hash = a144269e
vb1 = ResourceGorouTexcoord

[TextureOverrideGorouVertexLimitRaise]
hash = 955b7007

[TextureOverrideGorouIB]
hash = b2e57c84
handling = skip
drawindexed = auto

[TextureOverrideGorouHead]
hash = b2e57c84
match_first_index = 0
ib = ResourceGorouHeadIB
ps-t0 = ResourceGorouHeadDiffuse
ps-t1 = ResourceGorouHeadLightMap

[TextureOverrideGorouBody]
hash = b2e57c84
match_first_index = 8022
ib = ResourceGorouBodyIB
ps-t0 = ResourceGorouBodyDiffuse
ps-t1 = ResourceGorouBodyLightMap

[TextureOverrideGorouFaceHeadDiffuse]
hash = 5ee8444a
ps-t0 = ResourceGorouFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceGorouPosition]
type = Buffer
stride = 40
filename = GorouPosition.buf

[ResourceGorouBlend]
type = Buffer
stride = 32
filename = GorouBlend.buf

[ResourceGorouTexcoord]
type = Buffer
stride = 12
filename = GorouTexcoord.buf

[ResourceGorouHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = GorouHead.ib

[ResourceGorouBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = GorouBody.ib

[ResourceGorouHeadDiffuse]
filename = GorouHeadDiffuse.dds

[ResourceGorouHeadLightMap]
filename = GorouHeadLightMap.dds

[ResourceGorouBodyDiffuse]
filename = GorouBodyDiffuse.dds

[ResourceGorouBodyLightMap]
filename = GorouBodyLightMap.dds

[ResourceGorouFaceHeadDiffuse]
filename = GorouFaceHeadDiffuse.dds


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord