; Varesa

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideVaresaPosition]
hash = 9784dbe3
vb0 = ResourceVaresaPosition
$active = 1

[TextureOverrideVaresaBlend]
hash = ef26783e
vb1 = ResourceVaresaBlend
handling = skip
draw = 65357,0 

[TextureOverrideVaresaTexcoord]
hash = 0fa7f23f
vb1 = ResourceVaresaTexcoord

[TextureOverrideVaresaVertexLimitRaise]
hash = 8872531c
override_vertex_count = 65357
override_byte_stride = 84

[TextureOverrideVaresaIB]
hash = 488fceb4
handling = skip

[TextureOverrideVaresaHead]
hash = 488fceb4
match_first_index = 0
ib = ResourceVaresaHeadIB
; VaresaHead
	; Head (10706)
	drawindexed = 38346, 0, 0

[TextureOverrideVaresaBody]
hash = 488fceb4
match_first_index = 40554
ib = ResourceVaresaBodyIB
ps-t0 = ResourceVaresaBodyNormalMap
ps-t1 = ResourceVaresaBodyDiffuse
ps-t2 = ResourceVaresaBodyLightMap
ps-t8 = ResourceVaresaBodySkillMap
run = CommandList\global\ORFix\ORFix
; VaresaBody
	; Body (54651)
	drawindexed = 292875, 0, 0

; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
    pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
    pre run = CustomShader\ShaderFixes\help.ini\FormatText
    pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
    $creditinfo = 1
endif

; Resources -------------------------

[ResourceVaresaPosition]
type = Buffer
stride = 40
filename = VaresaPosition.buf

[ResourceVaresaBlend]
type = Buffer
stride = 32
filename = VaresaBlend.buf

[ResourceVaresaTexcoord]
type = Buffer
stride = 12
filename = VaresaTexcoord.buf

[ResourceVaresaHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = VaresaHead.ib

[ResourceVaresaBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = VaresaBody.ib

[ResourceVaresaBodyNormalMap]
filename = VaresaBodyNormalMap.dds

[ResourceVaresaBodyDiffuse]
filename = VaresaBodyDiffuse.dds

[ResourceVaresaBodyLightMap]
filename = VaresaBodyLightMap.dds

[ResourceVaresaBodySkillMap]
filename = VaresaBodySkillMap.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by patreon.com/tamayo_"

; .ini generated by XXMI (XX-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues