namespace = Ayato

; Constants ---------------------------

[Constants]
global persist $packvar = 0
global $active = 0
global $creditinfo = 0

[KeyPack]
condition = $active == 1
key = t
type = cycle
$packvar = 0,1,2
run = CommandListAyatoPack

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides ---------------------------

[TextureOverrideAyatoPosition]
hash = b473c856
if $packvar == 0
	run = commandlist\ayato\pack0\ayatoposition
elif $packvar == 1
	run = commandlist\ayato\pack1\ayatoposition
elif $packvar == 2
	run = commandlist\ayato\pack2\ayatoposition
endif
$active = 1

[TextureOverrideAyatoBlend]
hash = 19b13b6e
if $packvar == 0
	run = commandlist\ayato\pack0\ayatoblend
elif $packvar == 1
	run = commandlist\ayato\pack1\ayatoblend
elif $packvar == 2
	run = commandlist\ayato\pack2\ayatoblend
endif

[TextureOverrideAyatoTexcoord]
hash = 2482a5ee
if $packvar == 0
	run = commandlist\ayato\pack0\ayatotexcoord
elif $packvar == 1
	run = commandlist\ayato\pack1\ayatotexcoord
elif $packvar == 2
	run = commandlist\ayato\pack2\ayatotexcoord
endif

[TextureOverrideAyatoVertexLimitRaise]
hash = 36fca030

[TextureOverrideAyatoIB]
hash = e59b09d6
if $packvar == 0
	run = commandlist\ayato\pack0\ayatoib
elif $packvar == 1
	run = commandlist\ayato\pack1\ayatoib
elif $packvar == 2
	run = commandlist\ayato\pack2\ayatoib
endif

[TextureOverrideAyatoHead]
hash = e59b09d6
match_first_index = 0
if $packvar == 0
	run = commandlist\ayato\pack0\ayatohead
elif $packvar == 1
	run = commandlist\ayato\pack1\ayatohead
elif $packvar == 2
	run = commandlist\ayato\pack2\ayatohead
endif

[TextureOverrideAyatoBody]
hash = e59b09d6
match_first_index = 29769
if $packvar == 0
	run = commandlist\ayato\pack0\ayatobody
elif $packvar == 1
	run = commandlist\ayato\pack1\ayatobody
elif $packvar == 2
	run = commandlist\ayato\pack2\ayatobody
endif

[TextureOverrideAyatoDress]
hash = e59b09d6
match_first_index = 66183
if $packvar == 0
	run = commandlist\ayato\pack0\ayatodress
elif $packvar == 1
	run = commandlist\ayato\pack1\ayatodress
elif $packvar == 2
	run = commandlist\ayato\pack2\ayatodress
endif

[TextureOverrideAyatoFaceHeadDiffuse]
hash = 6e40e741
if $packvar == 0
	run = commandlist\ayato\pack0\ayatofaceheaddiffuse
elif $packvar == 1
	run = commandlist\ayato\pack1\ayatofaceheaddiffuse
elif $packvar == 2
	run = commandlist\ayato\pack2\ayatofaceheaddiffuse
endif

; CommandList -------------------------

[CommandListAyatoPack]
if $packvar == 0
	post Resource\ShaderFixes\help.ini\Notification = ResourceAyatoPack.0
elif $packvar == 1
	post Resource\ShaderFixes\help.ini\Notification = ResourceAyatoPack.1
elif $packvar == 2
	post Resource\ShaderFixes\help.ini\Notification = ResourceAyatoPack.2
endif
post run = CustomShader\ShaderFixes\help.ini\FormatText
post $\ShaderFixes\help.ini\notification_timeout = time + 5.0

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 1
endif

; Resources ---------------------------

[ResourceAyatoPack.0]
type = Buffer
data = "POSITION 2"

[ResourceAyatoPack.1]
type = Buffer
data = "HANDS FREE"

[ResourceAyatoPack.2]
type = Buffer
data = "HANDS ON ASS"

[ResourceCreditInfo]
type = Buffer
data = "Created mod by tedom"

; .ini generated by Discord Bot GI_Pack
