; Mavuika

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideMavuikaHairPosition]
hash = 039618b0
vb0 = ResourceMavuikaHairPosition
$active = 1

[TextureOverrideMavuikaHairBlend]
hash = 64424fcd
vb1 = ResourceMavuikaHairBlend
handling = skip
draw = 8829,0 

[TextureOverrideMavuikaHairTexcoord]
hash = 8403fb71
vb1 = ResourceMavuikaHairTexcoord

[TextureOverrideMavuikaHairVertexLimitRaise]
hash = 890ec94f
override_vertex_count = 8829
override_byte_stride = 84

[TextureOverrideMavuikaBodyPosition]
hash = 80b13a2f
vb0 = ResourceMavuikaBodyPosition
$active = 1

[TextureOverrideMavuikaBodyBlend]
hash = 00088f8d
vb1 = ResourceMavuikaBodyBlend
handling = skip
draw = 25829,0 

[TextureOverrideMavuikaBodyTexcoord]
hash = 3af262c1
vb1 = ResourceMavuikaBodyTexcoord

[TextureOverrideMavuikaBodyVertexLimitRaise]
hash = 00323c91
override_vertex_count = 25829
override_byte_stride = 84

[TextureOverrideMavuikaHairIB]
hash = f6c93dd3
handling = skip
drawindexed = auto

[TextureOverrideMavuikaHairHead]
hash = f6c93dd3
match_first_index = 0
ib = ResourceMavuikaHairHeadIB
ps-t0 = ResourceMavuikaHairHeadNormalMap
ps-t1 = ResourceMavuikaHairHeadDiffuse
ps-t2 = ResourceMavuikaHairHeadLightMap

[TextureOverrideMavuikaBodyIB]
hash = 43f8af29
handling = skip
drawindexed = auto

[TextureOverrideMavuikaBodyHead]
hash = 43f8af29
match_first_index = 0
ib = null
ps-t0 = ResourceMavuikaBodyHeadNormalMap
ps-t1 = ResourceMavuikaBodyHeadDiffuse
ps-t2 = ResourceMavuikaBodyHeadLightMap

[TextureOverrideMavuikaBodyBody]
hash = 43f8af29
match_first_index = 16914
ib = ResourceMavuikaBodyBodyIB
ps-t0 = ResourceMavuikaBodyBodyNormalMap
ps-t1 = ResourceMavuikaBodyBodyDiffuse
ps-t2 = ResourceMavuikaBodyBodyLightMap

[TextureOverrideMavuikaBodyDress]
hash = 43f8af29
match_first_index = 42618
ib = null
ps-t0 = ResourceMavuikaBodyDressNormalMap
ps-t1 = ResourceMavuikaBodyDressDiffuse
ps-t2 = ResourceMavuikaBodyDressLightMap

[TextureOverrideMavuikaFaceHeadDiffuse]
hash = 3a7e93c8
this = ResourceMavuikaFaceHeadDiffuse


[TextureOverrideMavuikaNatlanFXHeadShadow]
hash = b6b1dc80
this = ResourceMavuikaNatlanFXHeadShadow




; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
    pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
    pre run = CustomShader\ShaderFixes\help.ini\FormatText
    pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
    $creditinfo = 1
endif

; Resources -------------------------

[ResourceMavuikaHairPosition]
type = Buffer
stride = 40
filename = MavuikaHairPosition.buf

[ResourceMavuikaHairBlend]
type = Buffer
stride = 32
filename = MavuikaHairBlend.buf

[ResourceMavuikaHairTexcoord]
type = Buffer
stride = 12
filename = MavuikaHairTexcoord.buf

[ResourceMavuikaBodyPosition]
type = Buffer
stride = 40
filename = MavuikaBodyPosition.buf

[ResourceMavuikaBodyBlend]
type = Buffer
stride = 32
filename = MavuikaBodyBlend.buf

[ResourceMavuikaBodyTexcoord]
type = Buffer
stride = 12
filename = MavuikaBodyTexcoord.buf

[ResourceMavuikaHairHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MavuikaHairHead.ib

[ResourceMavuikaBodyHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MavuikaBodyHead.ib

[ResourceMavuikaBodyBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MavuikaBodyBody.ib

[ResourceMavuikaBodyDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MavuikaBodyDress.ib

[ResourceMavuikaHairHeadNormalMap]
filename = MavuikaHairHeadNormalMap.dds

[ResourceMavuikaHairHeadDiffuse]
filename = MavuikaHairHeadDiffuse.dds

[ResourceMavuikaHairHeadLightMap]
filename = MavuikaHairHeadLightMap.dds

[ResourceMavuikaBodyHeadNormalMap]
filename = MavuikaBodyHeadNormalMap.dds

[ResourceMavuikaBodyHeadDiffuse]
filename = MavuikaBodyHeadDiffuse.dds

[ResourceMavuikaBodyHeadLightMap]
filename = MavuikaBodyHeadLightMap.dds

[ResourceMavuikaBodyBodyNormalMap]
filename = MavuikaBodyBodyNormalMap.dds

[ResourceMavuikaBodyBodyDiffuse]
filename = MavuikaBodyBodyDiffuse.dds

[ResourceMavuikaBodyBodyLightMap]
filename = MavuikaBodyBodyLightMap.dds

[ResourceMavuikaBodyDressNormalMap]
filename = MavuikaBodyDressNormalMap.dds

[ResourceMavuikaBodyDressDiffuse]
filename = MavuikaBodyDressDiffuse.dds

[ResourceMavuikaBodyDressLightMap]
filename = MavuikaBodyDressLightMap.dds

[ResourceMavuikaFaceHeadDiffuse]
filename = MavuikaFaceHeadDiffuse.dds

[ResourceMavuikaNatlanFXHeadShadow]
filename = MavuikaNatlanFXHeadShadow.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by yzx"

; .ini generated by XXMI (XX-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues