; Lynette

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideLynettePosition]
hash = 98eb2db4
vb0 = ResourceLynettePosition
$active = 1

[TextureOverrideLynetteBlend]
hash = 42addacd
vb1 = ResourceLynetteBlend
handling = skip
draw = 79449, 0 

[TextureOverrideLynetteTexcoord]
hash = f828b5be
vb1 = ResourceLynetteTexcoord

[TextureOverrideLynetteVertexLimitRaise]
hash = 329f5c91

[TextureOverrideLynetteIB]
hash = 39d89255
handling = skip


[TextureOverrideLynetteHead]
hash = 39d89255
match_first_index = 0
ib = ResourceLynetteHeadIB
ps-t0 = ResourceLynetteHeadDiffuse
ps-t1 = ResourceLynetteHeadLightMap
run = CommandList\global\ORFix\NNFix
if $basebody == 1
  drawindexed = 16155, 0, 0
endif
if $bra1 == 1
  drawindexed = 6, 16155, 0
endif
if $bra2 == 1
  drawindexed = 6, 16161, 0
endif
if $pantsu1 == 1
  drawindexed = 6, 16167, 0
endif
if $pantsu2 == 1
  drawindexed = 6, 16173, 0
endif
if $glasses == 1
  drawindexed = 6, 16179, 0
endif
if $sweater1 == 1
  drawindexed = 114, 16185, 0
endif
if $sweater2 == 1
  drawindexed = 114, 16299, 0
endif
if $sweater3 == 1
  drawindexed = 114, 16413, 0
endif
if $sweater4 == 1
  drawindexed = 114, 16527, 0
endif
if $skirt == 1
  drawindexed = 6, 16641, 0
endif
if $thighhigh == 1
  drawindexed = 6, 16647, 0
endif
if $gloves == 1
  drawindexed = 6, 16653, 0
endif
if $shoe1 == 1
  drawindexed = 6, 16659, 0
endif
if $shoe2 == 1
  drawindexed = 6, 16665, 0
endif
if $scarf == 1
  drawindexed = 6, 16671, 0
endif


[TextureOverrideLynetteBody]
hash = 39d89255
match_first_index = 16257
ib = ResourceLynetteBodyIB
ps-t0 = ResourceLynetteBodyNormalMap
ps-t2 = ResourceLynetteBodyLightMap

if $color == 0
	ps-t1 = ResourceLynetteBodyDiffuse
else if $color == 1
 	ps-t1 = ResourceLynetteBodyDiffuse2
endif
run = CommandList\global\ORFix\ORFix
if $basebody == 1
  drawindexed = 145188, 0, 0
endif
if $bra1 == 1
  drawindexed = 6, 145188, 0
endif
if $bra2 == 1
  drawindexed = 6, 145194, 0
endif
if $pantsu1 == 1
  drawindexed = 6, 145200, 0
endif
if $pantsu2 == 1
  drawindexed = 6, 145206, 0
endif
if $glasses == 1
  drawindexed = 6, 145212, 0
endif
if $sweater1 == 1
  drawindexed = 6, 145218, 0
endif
if $sweater2 == 1
  drawindexed = 6, 145224, 0
endif
if $sweater3 == 1
  drawindexed = 6, 145230, 0
endif
if $sweater4 == 1
  drawindexed = 6, 145236, 0
endif
if $skirt == 1
  drawindexed = 6, 145242, 0
endif
if $thighhigh == 1
  drawindexed = 6, 145248, 0
endif
if $gloves == 1
  drawindexed = 6, 145254, 0
endif
if $shoe1 == 1
  drawindexed = 6, 145260, 0
endif
if $shoe2 == 1
  drawindexed = 6, 145266, 0
endif
if $scarf == 1
  drawindexed = 6, 145272, 0
endif



[TextureOverrideLynetteDress]
hash = 39d89255
match_first_index = 65223
ib = ResourceLynetteDressIB
ps-t0 = ResourceLynetteDressDiffuse
ps-t1 = ResourceLynetteDressLightMap
run = CommandList\global\ORFix\NNFix
if $basebody == 1
  drawindexed = 2286, 0, 0
endif
if $bra1 == 1
  drawindexed = 6, 2286, 0
endif
if $bra2 == 1
  drawindexed = 6, 2292, 0
endif
if $pantsu1 == 1
  drawindexed = 6, 2298, 0
endif
if $pantsu2 == 1
  drawindexed = 6, 2304, 0
endif
if $glasses == 1
  drawindexed = 6, 2310, 0
endif
if $sweater1 == 1
  drawindexed = 6, 2316, 0
endif
if $sweater2 == 1
  drawindexed = 6, 2322, 0
endif
if $sweater3 == 1
  drawindexed = 6, 2328, 0
endif
if $sweater4 == 1
  drawindexed = 6, 2334, 0
endif
if $skirt == 1
  drawindexed = 6, 2340, 0
endif
if $thighhigh == 1
  drawindexed = 6, 2346, 0
endif
if $gloves == 1
  drawindexed = 6, 2352, 0
endif
if $shoe1 == 1
  drawindexed = 6, 2358, 0
endif
if $shoe2 == 1
  drawindexed = 6, 2364, 0
endif
if $scarf == 1
  drawindexed = 6, 2370, 0
endif


[TextureOverrideLynetteExtra]
hash = 39d89255
match_first_index = 68358
ib = ResourceLynetteExtraIB
ps-t0 = ResourceLynetteExtraNormalMap
ps-t1 = ResourceLynetteExtraDiffuse
ps-t2 = ResourceLynetteExtraLightMap
run = CommandList\global\ORFix\ORFix
if $basebody == 1
  drawindexed = 6, 0, 0
endif
if $bra1 == 1
  drawindexed = 3582, 6, 0
endif
if $bra2 == 1
  drawindexed = 3582, 3588, 0
endif
if $pantsu1 == 1
  drawindexed = 4866, 7170, 0
endif
if $pantsu2 == 1
  drawindexed = 4866, 12036, 0
endif
if $glasses == 1
  drawindexed = 3066, 16902, 0
endif
if $sweater1 == 1
  drawindexed = 13056, 19968, 0
endif
if $sweater2 == 1
  drawindexed = 22197, 33024, 0
endif
if $sweater3 == 1
  drawindexed = 8796, 55221, 0
endif
if $sweater4 == 1
  drawindexed = 17937, 64017, 0
endif
if $skirt == 1
  drawindexed = 1476, 81954, 0
endif
if $thighhigh == 1
  drawindexed = 27714, 83430, 0
endif
if $gloves == 1
  drawindexed = 84450, 111144, 0
endif
if $shoe1 == 1
  drawindexed = 10200, 195594, 0
endif
if $shoe2 == 1
  drawindexed = 6402, 205794, 0
endif
if $scarf == 1
  drawindexed = 7218, 212196, 0
endif


; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 1
endif

; Resources -------------------------

[ResourceLynettePosition]
type = Buffer
stride = 40
filename = LynettePosition.buf

[ResourceLynetteBlend]
type = Buffer
stride = 32
filename = LynetteBlend.buf

[ResourceLynetteTexcoord]
type = Buffer
stride = 20
filename = LynetteTexcoord.buf

[ResourceLynetteHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LynetteHead.ib

[ResourceLynetteBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LynetteBody.ib

[ResourceLynetteDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LynetteDress.ib

[ResourceLynetteExtraIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LynetteExtra.ib

[ResourceLynetteHeadDiffuse]
filename = LynetteHeadDiffuse.dds

[ResourceLynetteHeadLightMap]
filename = LynetteHeadLightMap.dds

[ResourceLynetteBodyNormalMap]
filename = LynetteBodyNormalMap.dds

[ResourceLynetteBodyDiffuse]
filename = LynetteBodyDiffuse.dds

[ResourceLynetteBodyDiffuse2]
filename = LynetteBodyDiffuse2.dds

[ResourceLynetteBodyLightMap]
filename = LynetteBodyLightMap.dds

[ResourceLynetteDressDiffuse]
filename = LynetteDressDiffuse.dds

[ResourceLynetteDressLightMap]
filename = LynetteDressLightMap.dds

[ResourceLynetteExtraNormalMap]
filename = LynetteExtraNormalMap.dds

[ResourceLynetteExtraDiffuse]
filename = LynetteExtraDiffuse.dds

[ResourceLynetteExtraLightMap]
filename = LynetteExtraLightMap.dds

[ResourceCreditInfo]
type = Buffer
data = "Use H for info"


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord
[Constants]
global persist $basebody = 1
global persist $bra1 = 1
global persist $bra2 = 0
global persist $pantsu1 = 1
global persist $pantsu2 = 0
global persist $glasses = 1
global persist $sweater1 = 1
global persist $sweater2 = 0
global persist $sweater3 = 0
global persist $sweater4 = 0
global persist $skirt = 1
global persist $thighhigh = 1
global persist $gloves = 1
global persist $shoe1 = 1
global persist $shoe2 = 0
global persist $scarf = 1
global persist $color = 0

[KeyColor]
condition = $active == 1
key = y
type = cycle
$color = 0,1

[KeyBRA]
key = 6
condition = $active == 1
type = cycle
$bra1 = 0,1
$bra2 = 0,0,1

[KeySwap3]
key = 7
condition = $active == 1
type = cycle
$pantsu1 = 0,1
$pantsu2 = 0,0,1
[KeySwap5]
key = 8
condition = $active == 1
type = cycle
$glasses = 0,1

[KeySwap6]
key = 9
condition = $active == 1
type = cycle
$sweater1 = 0,1,0,0,0
$sweater2 = 0,0,1,0,0
$sweater3 = 0,0,0,1,0
$sweater4 = 0,0,0,0,1

[KeySwap10]
key = 0
condition = $active == 1
type = cycle
$skirt = 0,1

[KeySwap11]
key = _
condition = $active == 1
type = cycle
$thighhigh = 0,1

[KeySwap12]
key = =
condition = $active == 1
type = cycle
$gloves = 0,1

[KeySwap14]
key = t
condition = $active == 1
type = cycle
$shoe1 = 0,1,0
$shoe2 = 0,0,1 

[KeySwap15]
key = u
condition = $active == 1
type = cycle
$scarf = 0,1

[KeyNude]
key = n
condition = $active == 1
type = cycle
$gloves = 0,1,1
$scarf = 0,1,0
$shoe1 = 0,1,1
$shoe2 = 0,0,0
$thighhigh = 0,1,1
$skirt = 0,1,0
$glasses = 0,1,1
$pantsu1 = 0,1,1
$pantsu2 = 0,0,0
$bra1 = 0,1,1
$bra2 = 0,0,0
$sweater1 = 0,0,0
$sweater2 = 0,1,0
$sweater3 = 0,0,0
$sweater4 = 0,0,0