; Varesa

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideVaresaPosition]
hash = 9784dbe3
vb0 = ResourceVaresaPosition
$active = 1

[TextureOverrideVaresaBlend]
hash = ef26783e
vb1 = ResourceVaresaBlend
handling = skip
draw = 97923,0 

[TextureOverrideVaresaTexcoord]
hash = 0fa7f23f
vb1 = ResourceVaresaTexcoord

[TextureOverrideVaresaVertexLimitRaise]
hash = 8872531c
; override_vertex_count = 90648
; override_byte_stride = 84

[TextureOverrideVaresaIB]
hash = 488fceb4
handling = skip
drawindexed = auto

[TextureOverrideVaresaHead]
hash = 488fceb4
match_first_index = 0
ib = ResourceVaresaHeadIB
ps-t0 = ResourceVaresaHeadNormalMap
ps-t1 = ResourceVaresaHeadDiffuse
ps-t2 = ResourceVaresaHeadLightMap

[TextureOverrideVaresaBody]
hash = 488fceb4
match_first_index = 40554
ib = ResourceVaresaBodyIB
ps-t0 = ResourceVaresaBodyNormalMap
ps-t1 = ResourceVaresaBodyDiffuse
ps-t2 = ResourceVaresaBodyLightMap

[TextureOverrideVaresaFaceHeadDiffuse]
hash = 9a534567
this = ResourceVaresaFaceHeadDiffuse


[TextureOverrideVaresaNatlanFXHeadDiffuse]
hash = 47590010
this = ResourceVaresaNatlanFXHeadDiffuse



; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
    pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
    pre run = CustomShader\ShaderFixes\help.ini\FormatText
    pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
    $creditinfo = 1
endif

; Resources -------------------------

[ResourceVaresaPosition]
type = Buffer
stride = 40
filename = VaresaPosition.buf

[ResourceVaresaBlend]
type = Buffer
stride = 32
filename = VaresaBlend.buf

[ResourceVaresaTexcoord]
type = Buffer
stride = 12
filename = VaresaTexcoord.buf

[ResourceVaresaHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = VaresaHead.ib

[ResourceVaresaBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = VaresaBody.ib

[ResourceVaresaHeadNormalMap]
filename = VaresaHeadNormalMap.dds

[ResourceVaresaHeadDiffuse]
filename = VaresaHeadDiffuse.dds

[ResourceVaresaHeadLightMap]
filename = VaresaHeadLightMap.dds

[ResourceVaresaBodyNormalMap]
filename = VaresaBodyNormalMap.dds

[ResourceVaresaBodyDiffuse]
filename = VaresaBodyDiffuse.dds

[ResourceVaresaBodyLightMap]
filename = VaresaBodyLightMap.dds

[ResourceVaresaFaceHeadDiffuse]
filename = VaresaFaceHeadDiffuse.dds

[ResourceVaresaNatlanFXHeadDiffuse]
filename = VaresaNatlanFXHeadDiffuse.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by yzx"

; .ini generated by XXMI (XX-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues