; Jean

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideJeanPosition]
hash = 93bb2522
vb0 = ResourceJeanPosition
$active = 1

[TextureOverrideJeanBlend]
hash = d159bf31
vb1 = ResourceJeanBlend
handling = skip
draw = 111843,0 

[TextureOverrideJeanTexcoord]
hash = 0ffefb98
vb1 = ResourceJeanTexcoord

[TextureOverrideJeanVertexLimitRaise]
hash = a3cccc14
; override_vertex_count = 109621
; override_byte_stride = 84

[TextureOverrideJeanIB]
hash = aad861e0
handling = skip
drawindexed = auto

[TextureOverrideJeanHead]
hash = aad861e0
match_first_index = 0
ib = ResourceJeanHeadIB
ps-t0 = ResourceJeanHeadDiffuse
ps-t1 = ResourceJeanHeadLightMap

[TextureOverrideJeanBody]
hash = aad861e0
match_first_index = 7779
ib = ResourceJeanBodyIB
ps-t0 = ResourceJeanBodyDiffuse
ps-t1 = ResourceJeanBodyLightMap

; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
    pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
    pre run = CustomShader\ShaderFixes\help.ini\FormatText
    pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
    $creditinfo = 1
endif

; Resources -------------------------

[ResourceJeanPosition]
type = Buffer
stride = 40
filename = JeanPosition.buf

[ResourceJeanBlend]
type = Buffer
stride = 32
filename = JeanBlend.buf

[ResourceJeanTexcoord]
type = Buffer
stride = 12
filename = JeanTexcoord.buf

[ResourceJeanHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JeanHead.ib

[ResourceJeanBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JeanBody.ib

[ResourceJeanHeadDiffuse]
filename = JeanHeadDiffuse.dds

[ResourceJeanHeadLightMap]
filename = JeanHeadLightMap.dds

[ResourceJeanBodyDiffuse]
filename = JeanBodyDiffuse.dds

[ResourceJeanBodyLightMap]
filename = JeanBodyLightMap.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by yzx"

; .ini generated by XXMI (XX-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues