namespace = Childe

; Constants ---------------------------

[Constants]
global persist $packvar = 0
global $active = 0
global $creditinfo = 0

[KeyPack]
condition = $active == 1
key = t
back = r
type = cycle
$packvar = 0,1,2
run = CommandListChildePack

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides ---------------------------

[TextureOverrideChildePosition]
hash = 186eac84
if $packvar == 0
	run = commandlist\childe\pack0\childeposition
elif $packvar == 1
	run = commandlist\childe\pack1\childeposition
elif $packvar == 2
	run = commandlist\childe\pack2\childeposition
endif
$active = 1

[TextureOverrideChildeBlend]
hash = fff25ec8
if $packvar == 0
	run = commandlist\childe\pack0\childeblend
elif $packvar == 1
	run = commandlist\childe\pack1\childeblend
elif $packvar == 2
	run = commandlist\childe\pack2\childeblend
endif

[TextureOverrideChildeTexcoord]
hash = 7e7aeada
if $packvar == 0
	run = commandlist\childe\pack0\childetexcoord
elif $packvar == 1
	run = commandlist\childe\pack1\childetexcoord
elif $packvar == 2
	run = commandlist\childe\pack2\childetexcoord
endif

[TextureOverrideChildeVertexLimitRaise]
hash = f08f1c85

[TextureOverrideChildeScarfVertexLimitRaise]
hash = f32fdd67

[TextureOverrideChildeIB]
hash = 531d9358
if $packvar == 0
	run = commandlist\childe\pack0\childeib
elif $packvar == 1
	run = commandlist\childe\pack1\childeib
elif $packvar == 2
	run = commandlist\childe\pack2\childeib
endif

[TextureOverrideChildeHead]
hash = 531d9358
match_first_index = 0
if $packvar == 0
	run = commandlist\childe\pack0\childehead
elif $packvar == 1
	run = commandlist\childe\pack1\childehead
elif $packvar == 2
	run = commandlist\childe\pack2\childehead
endif

[TextureOverrideChildeBody]
hash = 531d9358
match_first_index = 9261
if $packvar == 0
	run = commandlist\childe\pack0\childebody
elif $packvar == 1
	run = commandlist\childe\pack1\childebody
elif $packvar == 2
	run = commandlist\childe\pack2\childebody
endif

[TextureOverrideChildeScarfBody]
hash = d7dd3b5f
;hash = ef095180
match_first_index = 549
if $packvar == 0
	run = commandlist\childe\pack0\childescarfbody
elif $packvar == 1
	run = commandlist\childe\pack1\childescarfbody
elif $packvar == 2
	run = commandlist\childe\pack2\childescarfbody
endif


[TextureOverrideChildescarfthingy]
hash = f32fdd67
handling = skip

; CommandList -------------------------

[CommandListChildePack]
if $packvar == 0
	post Resource\ShaderFixes\help.ini\Notification = ResourceChildePack.0
elif $packvar == 1
	post Resource\ShaderFixes\help.ini\Notification = ResourceChildePack.1
elif $packvar == 2
	post Resource\ShaderFixes\help.ini\Notification = ResourceChildePack.2
endif
post run = CustomShader\ShaderFixes\help.ini\FormatText
post $\ShaderFixes\help.ini\notification_timeout = time + 5.0

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 1
endif

; Resources ---------------------------

[ResourceChildePack.0]
type = Buffer
data = "position 2"

[ResourceChildePack.1]
type = Buffer
data = "Handonass"

[ResourceChildePack.2]
type = Buffer
data = "hands free"

[ResourceCreditInfo]
type = Buffer
data = "Created mod by tedom"

; .ini generated by Discord Bot GI_Pack
