; Xinyan

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideXinyanPosition]
hash = 76ed85f0
vb0 = ResourceXinyanPosition

[TextureOverrideXinyanBlend]
hash = f4b3fc47
vb1 = ResourceXinyanBlend
handling = skip
draw = 41771,0 

[TextureOverrideXinyanTexcoord]
hash = c07f3de3
vb1 = ResourceXinyanTexcoord

[TextureOverrideXinyanVertexLimitRaise]
hash = 93d428f4

[TextureOverrideXinyanIB]
hash = 97f78c9b
handling = skip
drawindexed = auto

[TextureOverrideXinyanHead]
hash = 97f78c9b
match_first_index = 0
ib = ResourceXinyanHeadIB
ps-t0 = ResourceXinyanHeadDiffuse
ps-t1 = ResourceXinyanHeadLightMap

[TextureOverrideXinyanBody]
hash = 97f78c9b
match_first_index = 21852
ib = ResourceXinyanBodyIB
ps-t0 = ResourceXinyanBodyDiffuse
ps-t1 = ResourceXinyanBodyLightMap

[TextureOverrideXinyanFaceHeadDiffuse]
hash = 859680fe
ps-t0 = ResourceXinyanFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceXinyanPosition]
type = Buffer
stride = 40
filename = XinyanPosition.buf

[ResourceXinyanBlend]
type = Buffer
stride = 32
filename = XinyanBlend.buf

[ResourceXinyanTexcoord]
type = Buffer
stride = 12
filename = XinyanTexcoord.buf

[ResourceXinyanHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XinyanHead.ib

[ResourceXinyanBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XinyanBody.ib

[ResourceXinyanHeadDiffuse]
filename = XinyanHeadDiffuse.dds

[ResourceXinyanHeadLightMap]
filename = XinyanHeadLightMap.dds

[ResourceXinyanBodyDiffuse]
filename = XinyanBodyDiffuse.dds

[ResourceXinyanBodyLightMap]
filename = XinyanBodyLightMap.dds

[ResourceXinyanFaceHeadDiffuse]
filename = XinyanFaceHeadDiffuse.dds


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord