; Zibai

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0
global persist $top = 0
global persist $bottom = 0
global persist $tail = 0
global persist $neck = 0

[Keytop]
condition = $active == 1
key = y
type = cycle
$top = 0,1
$creditinfo = 0

[Keybottom]
condition = $active == 1
key = h
type = cycle
$bottom = 0,1
$creditinfo = 0

[Keytail]
condition = $active == 1
key = n
type = cycle
$tail = 0,1
$creditinfo = 0

[Keyneck]
condition = $active == 1
key = 6
type = cycle
$neck = 0,1,2,3
$creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideZibaiHeadPosition]
hash = 4a9f2849
vb0 = ResourceZibaiHeadPosition
$active = 1

[TextureOverrideZibaiHeadBlend]
hash = 8bf96d39
handling = skip
vb1 = ResourceZibaiHeadBlend
draw = 3101, 0

[TextureOverrideZibaiHeadTexcoord]
hash = 8b0db168
vb1 = ResourceZibaiHeadTexcoord

[TextureOverrideZibaiHeadVertexLimitRaise]
hash = 5252b00f
override_vertex_count = 3101
override_byte_stride = 40

[TextureOverrideZibaiBodyPosition]
hash = 01e37562
vb0 = ResourceZibaiBodyPosition
$active = 1

[TextureOverrideZibaiBodyBlend]
hash = cc1315e7
handling = skip
vb1 = ResourceZibaiBodyBlend
draw = 70063, 0

[TextureOverrideZibaiBodyTexcoord]
hash = 8e67410a
vb1 = ResourceZibaiBodyTexcoord

[TextureOverrideZibaiBodyVertexLimitRaise]
hash = c9189b30
override_vertex_count = 70063
override_byte_stride = 40

[TextureOverrideZibaiTailPosition]
hash = 80c3351a
vb0 = ResourceZibaiTailPosition
$active = 1

[TextureOverrideZibaiTailBlend]
hash = 527fab51
handling = skip
vb1 = ResourceZibaiTailBlend
draw = 51, 0

[TextureOverrideZibaiTailTexcoord]
hash = 94f65169
vb1 = ResourceZibaiTailTexcoord

[TextureOverrideZibaiTailVertexLimitRaise]
hash = c94c87fa
override_vertex_count = 51
override_byte_stride = 40

[TextureOverrideZibaiHeadIB]
hash = 58e7c1e4
handling = skip

[TextureOverrideZibaiHeadA]
hash = 58e7c1e4
match_first_index = 0
ib = ResourceZibaiHeadAIB
ps-t2 = ResourceZibaiHeadALightMap
ps-t0 = ResourceZibaiHeadANormalMap
ps-t1 = ResourceZibaiHeadADiffuse
run = CommandList\global\ORFix\ORFix
; ZB Hair Bangs (3101)
drawindexed = 11538, 0, 0

[TextureOverrideZibaiBodyIB]
hash = 111627bf
handling = skip

[TextureOverrideZibaiBodyA]
hash = 111627bf
match_first_index = 0
ib = ResourceZibaiBodyAIB
; ZB Hair Back (5730)
drawindexed = 21837, 0, 0
; ZB Hands.Decorations (5618)
drawindexed = 22452, 21837, 0
; ZB Hands.Nails (190)
drawindexed = 540, 44289, 0


if $top == 0 || $top == 2
; ZB Vision (926)
drawindexed = 2652, 44829, 0
endif

[TextureOverrideZibaiBodyB]
hash = 111627bf
match_first_index = 50673
ib = ResourceZibaiBodyBIB
ps-t2 = ResourceZibaiBodyBLightMap
ps-t0 = ResourceZibaiBodyBNormalMap
ps-t1 = ResourceZibaiBodyBDiffuse
run = CommandList\global\ORFix\ORFix
; ZB Armbands (1350)
drawindexed = 4056, 0, 0
; ZB Sandals (5105)
drawindexed = 24456, 83619, 0

if $top == 0
; ZB Bikini Top (6227)
drawindexed = 29346, 43668, 0
; ZiBai Chest.InDress (4269)
drawindexed = 23130, 142047, 0
elif $top == 1
; ZiBai Chest.Exposed (4269)
drawindexed = 23130, 118917, 0
; ZiBai Nipples.Exposed (434)
drawindexed = 2376, 188583, 0
endif

if $bottom == 0
; ZB Bikini Bottom (8684)
drawindexed = 39612, 4056, 0
; ZiBai Pelvis (7663)
drawindexed = 40458, 190959, 0
elif $bottom == 1
; ZiBai Pelvis.Exposed (7663)
drawindexed = 40458, 231417, 0
endif

if $neck == 0
; ZB Necklace Medallion (651)
drawindexed = 2568, 81051, 0
elif $neck == 1
; ZB Moon Choker (436)
drawindexed = 1332, 79719, 0
elif $neck == 2
; ZB Moon Choker (436)
drawindexed = 1332, 79719, 0
; ZB Necklace Medallion (651)
drawindexed = 2568, 81051, 0
elif $neck == 3
endif

; ZB Body Hair Ribbon (440)
drawindexed = 1653, 73014, 0
; ZB Boot Pompoms (420)
drawindexed = 2040, 74667, 0

if $bottom == 0
; ZB Hip Ornament (731)
drawindexed = 3012, 76707, 0
endif

if $tail ==0
; ZB Tail.Moons (629)
drawindexed = 1530, 108075, 0
endif

; ZB Thigh Bands Filligreed (2324)
drawindexed = 6288, 109605, 0
; ZiBai Arms (704)
drawindexed = 3024, 115893, 0

; ZiBai Feet.Sandals (1268)
drawindexed = 5220, 165177, 0
; ZiBai Hands (1763)
drawindexed = 7224, 170397, 0
; ZiBai Legs (1631)
drawindexed = 8586, 177621, 0
; ; ZiBai Nipples (434)
; drawindexed = 2376, 186207, 0


[TextureOverrideZibaiBodyD]
hash = 111627bf
match_first_index = 97299
ib = ResourceZibaiBodyDIB
ps-t2 = ResourceZibaiBodyBLightMap
ps-t0 = ResourceZibaiBodyBNormalMap
ps-t1 = ResourceZibaiBodyBDiffuse
run = CommandList\global\ORFix\ORFix
; ZB Hair Main Moon Ornaments (168)
drawindexed = 468, 0, 0
; ZB Hair Ribbon Moon Ornaments.001 (164)
drawindexed = 432, 468, 0

if $bottom == 0
; ZB Hip Moon Ornament (172)
drawindexed = 450, 900, 0
endif

[TextureOverrideZibaiTailIB]
hash = 8dbee173
handling = skip

[TextureOverrideZibaiTailA]
hash = 8dbee173
match_first_index = 0
ib = ResourceZibaiTailAIB

if $tail == 0
; ZB Dress Tail (51)
drawindexed = 192, 0, 0
endif

[TextureOverrideZibaiChestVeilIB]
hash = e3d9940f
handling = skip


; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active > 0
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 2
endif

; Resources -------------------------

[ResourceZibaiHeadPosition]
type = Buffer
stride = 40
filename = ZibaiHeadPosition.buf

[ResourceZibaiHeadBlend]
type = Buffer
stride = 32
filename = ZibaiHeadBlend.buf

[ResourceZibaiHeadTexcoord]
type = Buffer
stride = 12
filename = ZibaiHeadTexcoord.buf

[ResourceZibaiHeadAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ZibaiHeadA.ib

[ResourceZibaiBodyPosition]
type = Buffer
stride = 40
filename = ZibaiBodyPosition.buf

[ResourceZibaiBodyBlend]
type = Buffer
stride = 32
filename = ZibaiBodyBlend.buf

[ResourceZibaiBodyTexcoord]
type = Buffer
stride = 20
filename = ZibaiBodyTexcoord.buf

[ResourceZibaiBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ZibaiBodyA.ib

[ResourceZibaiBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ZibaiBodyB.ib

[ResourceZibaiBodyCIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ZibaiBodyC.ib

[ResourceZibaiBodyDIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ZibaiBodyD.ib

[ResourceZibaiTailPosition]
type = Buffer
stride = 40
filename = ZibaiTailPosition.buf

[ResourceZibaiTailBlend]
type = Buffer
stride = 32
filename = ZibaiTailBlend.buf

[ResourceZibaiTailTexcoord]
type = Buffer
stride = 20
filename = ZibaiTailTexcoord.buf

[ResourceZibaiTailAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ZibaiTailA.ib

[ResourceZibaiHeadALightMap]
filename = ZibaiHeadALightMap.dds

[ResourceZibaiHeadANormalMap]
filename = ZibaiHeadANormalMap.dds

[ResourceZibaiHeadADiffuse]
filename = ZibaiHeadADiffuse.dds

[ResourceZibaiBodyBLightMap]
filename = ZibaiBodyBLightMap.dds

[ResourceZibaiBodyBNormalMap]
filename = ZibaiBodyBNormalMap.dds

[ResourceZibaiBodyBDiffuse]
filename = ZibaiBodyBDiffuse.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by www.patreon.com/lewd_lad || https://lewdlad.fanbox.cc/"

; .ini generated by XXMI (XX-Model-Importer) v1.6.3
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues



;NEW AND UNUSED

