; SangonomiyaKokomi

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideSangonomiyaKokomiPosition]
hash = dde4750a
vb0 = ResourceSangonomiyaKokomiPosition
$active = 1

[TextureOverrideSangonomiyaKokomiBlend]
hash = 7b61fb15
vb1 = ResourceSangonomiyaKokomiBlend
handling = skip
draw = 32064,0 

[TextureOverrideSangonomiyaKokomiTexcoord]
hash = 4ed0c9f8
vb1 = ResourceSangonomiyaKokomiTexcoord

[TextureOverrideSangonomiyaKokomiVertexLimitRaise]
hash = 66c6fb0a
; override_vertex_count = 6399
; override_byte_stride = 92

[TextureOverrideSangonomiyaKokomiIB]
hash = 74900c81
handling = skip
drawindexed = auto

[TextureOverrideSangonomiyaKokomiHead]
hash = 74900c81
match_first_index = 0
ib = ResourceSangonomiyaKokomiHeadIB
ps-t0 = ResourceSangonomiyaKokomiHeadDiffuse
ps-t1 = ResourceSangonomiyaKokomiHeadLightMap

[TextureOverrideSangonomiyaKokomiBody]
hash = 74900c81
match_first_index = 26424
ib = ResourceSangonomiyaKokomiBodyIB
ps-t0 = ResourceSangonomiyaKokomiBodyDiffuse
ps-t1 = ResourceSangonomiyaKokomiBodyLightMap

[TextureOverrideSangonomiyaKokomiDress]
hash = 74900c81
match_first_index = 52290
ib = ResourceSangonomiyaKokomiDressIB
ps-t0 = ResourceSangonomiyaKokomiDressDiffuse
ps-t1 = ResourceSangonomiyaKokomiDressLightMap

[TextureOverrideSangonomiyaKokomiFaceHeadDiffuse]
hash = 394fb133
this = ResourceSangonomiyaKokomiFaceHeadDiffuse


; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
    pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
    pre run = CustomShader\ShaderFixes\help.ini\FormatText
    pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
    $creditinfo = 1
endif

; Resources -------------------------

[ResourceSangonomiyaKokomiPosition]
type = Buffer
stride = 40
filename = SangonomiyaKokomiPosition.buf

[ResourceSangonomiyaKokomiBlend]
type = Buffer
stride = 32
filename = SangonomiyaKokomiBlend.buf

[ResourceSangonomiyaKokomiTexcoord]
type = Buffer
stride = 20
filename = SangonomiyaKokomiTexcoord.buf

[ResourceSangonomiyaKokomiHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SangonomiyaKokomiHead.ib

[ResourceSangonomiyaKokomiBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SangonomiyaKokomiBody.ib

[ResourceSangonomiyaKokomiDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SangonomiyaKokomiDress.ib

[ResourceSangonomiyaKokomiHeadDiffuse]
filename = SangonomiyaKokomiHeadDiffuse.dds

[ResourceSangonomiyaKokomiHeadLightMap]
filename = SangonomiyaKokomiHeadLightMap.dds

[ResourceSangonomiyaKokomiBodyDiffuse]
filename = SangonomiyaKokomiBodyDiffuse.dds

[ResourceSangonomiyaKokomiBodyLightMap]
filename = SangonomiyaKokomiBodyLightMap.dds

[ResourceSangonomiyaKokomiDressDiffuse]
filename = SangonomiyaKokomiDressDiffuse.dds

[ResourceSangonomiyaKokomiDressLightMap]
filename = SangonomiyaKokomiDressLightMap.dds

[ResourceSangonomiyaKokomiFaceHeadDiffuse]
filename = SangonomiyaKokomiFaceHeadDiffuse.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by yzx"

; .ini generated by XXMI (XX-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues