; Ineffa

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideIneffaEyesPosition]
hash = 1a349f1a
vb0 = ResourceIneffaEyesPosition
$active = 1

[TextureOverrideIneffaEyesBlend]
hash = 40db7601
vb1 = ResourceIneffaEyesBlend
handling = skip
draw = 352,0 

[TextureOverrideIneffaEyesTexcoord]
hash = 15a5fcbd
vb1 = ResourceIneffaEyesTexcoord

[TextureOverrideIneffaEyesVertexLimitRaise]
hash = 8d301b5f
override_vertex_count = 352
override_byte_stride = 84

[TextureOverrideIneffaBangsPosition]
hash = 3ee713f6
vb0 = ResourceIneffaBangsPosition
$active = 1

[TextureOverrideIneffaBangsBlend]
hash = 8669a384
vb1 = ResourceIneffaBangsBlend
handling = skip
draw = 1335,0 

[TextureOverrideIneffaBangsTexcoord]
hash = 7c9eba19
vb1 = ResourceIneffaBangsTexcoord

[TextureOverrideIneffaBangsVertexLimitRaise]
hash = aa601a29
override_vertex_count = 1335
override_byte_stride = 84

[TextureOverrideIneffaBodyPosition]
hash = 29fbb239
vb0 = ResourceIneffaBodyPosition
$active = 1

[TextureOverrideIneffaBodyBlend]
hash = 564782bd
vb1 = ResourceIneffaBodyBlend
handling = skip
draw = 94083,0 

[TextureOverrideIneffaBodyTexcoord]
hash = 7218d26f
vb1 = ResourceIneffaBodyTexcoord

[TextureOverrideIneffaBodyVertexLimitRaise]
hash = 52e2e822
override_vertex_count = 94083
override_byte_stride = 84

[TextureOverrideIneffaEyesIB]
hash = 6f8c4af6
handling = skip
drawindexed = auto

[TextureOverrideIneffaEyesA]
hash = 6f8c4af6
match_first_index = 0
ib = ResourceIneffaEyesAIB
ps-t0 = ResourceIneffaEyesADiffuse
ps-t1 = ResourceIneffaEyesALightMap

[TextureOverrideIneffaBangsIB]
hash = 79353adc
handling = skip
drawindexed = auto

[TextureOverrideIneffaBangsA]
hash = 79353adc
match_first_index = 0
ib = ResourceIneffaBangsAIB
ps-t0 = ResourceIneffaBangsANormalMap
ps-t1 = ResourceIneffaBangsADiffuse
ps-t2 = ResourceIneffaBangsALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIneffaBodyIB]
hash = 8a61684d
handling = skip
drawindexed = auto

[TextureOverrideIneffaBodyA]
hash = 8a61684d
match_first_index = 0
ib = ResourceIneffaBodyAIB
ps-t0 = ResourceIneffaBodyANormalMap
ps-t1 = ResourceIneffaBodyADiffuse
ps-t2 = ResourceIneffaBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIneffaBodyB]
hash = 8a61684d
match_first_index = 26166
ib = ResourceIneffaBodyBIB
ps-t0 = ResourceIneffaBodyBNormalMap
ps-t1 = ResourceIneffaBodyBDiffuse
ps-t2 = ResourceIneffaBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIneffaFaceADiffuse]
hash = 0332eeca
this = ResourceIneffaFaceADiffuse


; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
    pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
    pre run = CustomShader\ShaderFixes\help.ini\FormatText
    pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
    $creditinfo = 1
endif

; Resources -------------------------

[ResourceIneffaEyesPosition]
type = Buffer
stride = 40
filename = IneffaEyesPosition.buf

[ResourceIneffaEyesBlend]
type = Buffer
stride = 32
filename = IneffaEyesBlend.buf

[ResourceIneffaEyesTexcoord]
type = Buffer
stride = 12
filename = IneffaEyesTexcoord.buf

[ResourceIneffaBangsPosition]
type = Buffer
stride = 40
filename = IneffaBangsPosition.buf

[ResourceIneffaBangsBlend]
type = Buffer
stride = 32
filename = IneffaBangsBlend.buf

[ResourceIneffaBangsTexcoord]
type = Buffer
stride = 12
filename = IneffaBangsTexcoord.buf

[ResourceIneffaBodyPosition]
type = Buffer
stride = 40
filename = IneffaBodyPosition.buf

[ResourceIneffaBodyBlend]
type = Buffer
stride = 32
filename = IneffaBodyBlend.buf

[ResourceIneffaBodyTexcoord]
type = Buffer
stride = 12
filename = IneffaBodyTexcoord.buf

[ResourceIneffaEyesAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IneffaEyesA.ib

[ResourceIneffaBangsAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IneffaBangsA.ib

[ResourceIneffaBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IneffaBodyA.ib

[ResourceIneffaBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IneffaBodyB.ib

[ResourceIneffaEyesADiffuse]
filename = IneffaEyesADiffuse.dds

[ResourceIneffaEyesALightMap]
filename = IneffaEyesALightMap.dds

[ResourceIneffaBangsANormalMap]
filename = IneffaBangsANormalMap.dds

[ResourceIneffaBangsADiffuse]
filename = IneffaBangsADiffuse.dds

[ResourceIneffaBangsALightMap]
filename = IneffaBangsALightMap.dds

[ResourceIneffaBodyANormalMap]
filename = IneffaBodyANormalMap.dds

[ResourceIneffaBodyADiffuse]
filename = IneffaBodyADiffuse.dds

[ResourceIneffaBodyALightMap]
filename = IneffaBodyALightMap.dds

[ResourceIneffaBodyBNormalMap]
filename = IneffaBodyBNormalMap.dds

[ResourceIneffaBodyBDiffuse]
filename = IneffaBodyBDiffuse.dds

[ResourceIneffaBodyBLightMap]
filename = IneffaBodyBLightMap.dds

[ResourceIneffaFaceADiffuse]
filename = IneffaFaceADiffuse.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by yzx"

; .ini generated by XXMI (XX-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues