namespace = Neuvillette

; Constants ---------------------------

[Constants]
global persist $packvar = 0
global $active = 0
global $creditinfo = 0

[KeyPack]
condition = $active == 1
key = t
back = r
type = cycle
$packvar = 0,1,2,3,4
run = CommandListNeuvillettePack

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides ---------------------------

[TextureOverrideNeuvillettePosition]
hash = cad3a022
if $packvar == 0
	run = commandlist\neuvillette\pack0\neuvilletteposition
elif $packvar == 1
	run = commandlist\neuvillette\pack1\neuvilletteposition
elif $packvar == 2
	run = commandlist\neuvillette\pack2\neuvilletteposition
elif $packvar == 3
	run = commandlist\neuvillette\pack3\neuvilletteposition
elif $packvar == 4
	run = commandlist\neuvillette\pack4\neuvilletteposition
endif
$active = 1

[TextureOverrideNeuvilletteBlend]
hash = f060f732
if $packvar == 0
	run = commandlist\neuvillette\pack0\neuvilletteblend
elif $packvar == 1
	run = commandlist\neuvillette\pack1\neuvilletteblend
elif $packvar == 2
	run = commandlist\neuvillette\pack2\neuvilletteblend
elif $packvar == 3
	run = commandlist\neuvillette\pack3\neuvilletteblend
elif $packvar == 4
	run = commandlist\neuvillette\pack4\neuvilletteblend
endif

[TextureOverrideNeuvilletteTexcoord]
hash = ea5c17ee
if $packvar == 0
	run = commandlist\neuvillette\pack0\neuvillettetexcoord
elif $packvar == 1
	run = commandlist\neuvillette\pack1\neuvillettetexcoord
elif $packvar == 2
	run = commandlist\neuvillette\pack2\neuvillettetexcoord
elif $packvar == 3
	run = commandlist\neuvillette\pack3\neuvillettetexcoord
elif $packvar == 4
	run = commandlist\neuvillette\pack4\neuvillettetexcoord
endif

[TextureOverrideNeuvilletteVertexLimitRaise]
hash = 550c9ae1

[TextureOverrideNeuvilletteIB]
hash = f055eadd
if $packvar == 0
	run = commandlist\neuvillette\pack0\neuvilletteib
elif $packvar == 1
	run = commandlist\neuvillette\pack1\neuvilletteib
elif $packvar == 2
	run = commandlist\neuvillette\pack2\neuvilletteib
elif $packvar == 3
	run = commandlist\neuvillette\pack3\neuvilletteib
elif $packvar == 4
	run = commandlist\neuvillette\pack4\neuvilletteib
endif

[TextureOverrideNeuvilletteHead]
hash = f055eadd
match_first_index = 0
if $packvar == 0
	run = commandlist\neuvillette\pack0\neuvillettehead
elif $packvar == 1
	run = commandlist\neuvillette\pack1\neuvillettehead
elif $packvar == 2
	run = commandlist\neuvillette\pack2\neuvillettehead
elif $packvar == 3
	run = commandlist\neuvillette\pack3\neuvillettehead
elif $packvar == 4
	run = commandlist\neuvillette\pack4\neuvillettehead
endif

$CharacterIB = 1
ResourceRefHeadDiffuse = reference ps-t1
ResourceRefHeadLightMap = reference ps-t2

[TextureOverrideNeuvilletteBody]
hash = f055eadd
match_first_index = 33879
if $packvar == 0
	run = commandlist\neuvillette\pack0\neuvillettebody
elif $packvar == 1
	run = commandlist\neuvillette\pack1\neuvillettebody
elif $packvar == 2
	run = commandlist\neuvillette\pack2\neuvillettebody
elif $packvar == 3
	run = commandlist\neuvillette\pack3\neuvillettebody
elif $packvar == 4
	run = commandlist\neuvillette\pack4\neuvillettebody
endif

$CharacterIB = 2
ResourceRefBodyDiffuse = reference ps-t1
ResourceRefBodyLightMap = reference ps-t2

[TextureOverrideNeuvilletteDress]
hash = f055eadd
match_first_index = 79377
if $packvar == 0
	run = commandlist\neuvillette\pack0\neuvillettedress
elif $packvar == 1
	run = commandlist\neuvillette\pack1\neuvillettedress
elif $packvar == 2
	run = commandlist\neuvillette\pack2\neuvillettedress
elif $packvar == 3
	run = commandlist\neuvillette\pack3\neuvillettedress
elif $packvar == 4
	run = commandlist\neuvillette\pack4\neuvillettedress
endif

$CharacterIB = 3
ResourceRefDressDiffuse = reference ps-t1
ResourceRefDressLightMap = reference ps-t2

[TextureOverrideNeuvilletteFaceHeadDiffuse]
hash = 81e80510
if $packvar == 0
	run = commandlist\neuvillette\pack0\neuvillettefaceheaddiffuse
elif $packvar == 1
	run = commandlist\neuvillette\pack1\neuvillettefaceheaddiffuse
elif $packvar == 2
	run = commandlist\neuvillette\pack2\neuvillettefaceheaddiffuse
elif $packvar == 3
	run = commandlist\neuvillette\pack3\neuvillettefaceheaddiffuse
elif $packvar == 4
	run = commandlist\neuvillette\pack4\neuvillettefaceheaddiffuse
endif

; CommandList -------------------------

[CommandListNeuvillettePack]
if $packvar == 0
	post Resource\ShaderFixes\help.ini\Notification = ResourceNeuvillettePack.0
elif $packvar == 1
	post Resource\ShaderFixes\help.ini\Notification = ResourceNeuvillettePack.1
elif $packvar == 2
	post Resource\ShaderFixes\help.ini\Notification = ResourceNeuvillettePack.2
elif $packvar == 3
	post Resource\ShaderFixes\help.ini\Notification = ResourceNeuvillettePack.3
elif $packvar == 4
	post Resource\ShaderFixes\help.ini\Notification = ResourceNeuvillettePack.4
endif
post run = CustomShader\ShaderFixes\help.ini\FormatText
post $\ShaderFixes\help.ini\notification_timeout = time + 5.0

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 1
endif

; Resources ---------------------------

[ResourceNeuvillettePack.0]
type = Buffer
data = "position 2"

[ResourceNeuvillettePack.1]
type = Buffer
data = "position 3"

[ResourceNeuvillettePack.2]
type = Buffer
data = "BLOWJOB"

[ResourceNeuvillettePack.3]
type = Buffer
data = "hands off ass"

[ResourceNeuvillettePack.4]
type = Buffer
data = "Hands on ass"

[ResourceCreditInfo]
type = Buffer
data = "Created mod by tedom"

; .ini generated by Discord Bot GI_Pack


; Version 1.0.0 AGMG Tool Developer Version 3 Shader Fixer


; Generated shader fix for 3.0+ GIMI importer characters. Please contact the tool developers at https://discord.gg/agmg if you have any questions.

; Variables -----------------------

[Constants]
global $CharacterIB
;0=none, 1=head, 2=body, 3=dress, 4=extra, etc.

[Present]
post $CharacterIB = 0

[ResourceRefHeadDiffuse]
;[ResourceRefHeadLightMap]
[ResourceRefBodyDiffuse]
;[ResourceRefBodyLightMap]
[ResourceRefDressDiffuse]
;[ResourceRefDressLightMap]
[ResourceRefExtraDiffuse]
;[ResourceRefExtraLightMap]

; ShaderOverride ---------------------------

[ShaderRegexCharReflection]
shader_model = ps_5_0
run = CommandListReflectionTexture
[ShaderRegexCharReflection.pattern]
mul r\d+\.\w+, r\d+\.\w+,[^.]*\.\w+\n
mad o\d+\.\w+, r\d+\.\w+, cb\d+\[\d+\]\.\w+, r\d+\.\w+\n
mov o\d+\.\w+, l\(\d+\.\d+\)\n

;[ShaderRegexCharOutline]
;shader_model = ps_5_0
;run = CommandListOutline
;[ShaderRegexCharOutline.pattern]
;mov o\d+\.\w+, l\(\d+\)\n
;mov o\d+\.\w+, r\d+\.\w+\n
;mov o\d+\.\w+, l\(\d+\.\d+\)
;broken as of version 4.0

; OPTIONAL: If regex match breaks, use a [ShaderOverride] command matching shader hash for reflection then use "run = CommandListOutline" under the command

; CommandList -------------------------

[CommandListReflectionTexture]
if $CharacterIB != 0
    if $CharacterIB == 1
        ps-t0 = copy ResourceRefHeadDiffuse
    else if $CharacterIB == 2
        ps-t0 = copy ResourceRefBodyDiffuse
    else if $CharacterIB == 3
        ps-t0 = copy ResourceRefDressDiffuse
    else if $CharacterIB == 4
        ps-t0 = copy ResourceRefExtraDiffuse    
    endif
drawindexed=auto
$CharacterIB = 0
endif

;[CommandListOutline]
;if $CharacterIB != 0
;    if $CharacterIB == 1
;        ps-t1 = copy ResourceRefHeadLightMap
;    else if $CharacterIB == 2
;        ps-t1 = copy ResourceRefBodyLightMap
;    else if $CharacterIB == 3
;        ps-t1 = copy ResourceRefDressLightMap
;    else if $CharacterIB == 4
;        ps-t1 = copy ResourceRefExtraLightMap
;    endif
;drawindexed=auto
;$CharacterIB = 0
;endif
