; LaumaAntlers

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0

; Overrides -------------------------

[TextureOverrideLaumaAntlersPosition]
hash = 504a7d20
vb0 = ResourceLaumaAntlersPosition
$active = 1

[TextureOverrideLaumaAntlersBlend]
hash = a68439ae
vb1 = ResourceLaumaAntlersBlend
handling = skip
draw = 2309,0 

[TextureOverrideLaumaAntlersTexcoord]
hash = 59660493
vb1 = ResourceLaumaAntlersTexcoord

[TextureOverrideLaumaAntlersVertexLimitRaise]
hash = 65a0e51a
; override_vertex_count = 2309
; override_byte_stride = 84

[TextureOverrideLaumaAntlersIB]
hash = 7306ff89
handling = skip

[TextureOverrideLaumaAntlersHead]
hash = 7306ff89
match_first_index = 0
ib = ResourceLaumaAntlersHeadIB
ps-t0 = ResourceLaumaAntlersHeadDiffuse
ps-t1 = ResourceLaumaAntlersHeadLightMap
; LaumaAntlersHead
	; Antlers (2309)
	drawindexed = 7308, 0, 0

; CommandList -----------------------

; Resources -------------------------

[ResourceLaumaAntlersPosition]
type = Buffer
stride = 40
filename = .\Antlers\LaumaAntlersPosition.buf

[ResourceLaumaAntlersBlend]
type = Buffer
stride = 32
filename = .\Antlers\LaumaAntlersBlend.buf

[ResourceLaumaAntlersTexcoord]
type = Buffer
stride = 12
filename = .\Antlers\LaumaAntlersTexcoord.buf

[ResourceLaumaAntlersHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\Antlers\LaumaAntlersHead.ib

[ResourceLaumaAntlersHeadDiffuse]
filename = .\Textures\LaumaBodyB_D.dds

[ResourceLaumaAntlersHeadLightMap]
filename = .\Textures\LaumaBodyB_LP.dds

[ResourceCreditInfo]
type = Buffer
data = "Created by KiberSkyDen"

; .ini generated by XXMI (XX-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues