; RaidenShogun

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideRaidenShogunPosition]
hash = e48c61f3
vb0 = ResourceRaidenShogunPosition

[TextureOverrideRaidenShogunBlend]
hash = 1a495487
vb1 = ResourceRaidenShogunBlend
handling = skip
draw = 22906,0 

[TextureOverrideRaidenShogunTexcoord]
hash = 0c37fc86
vb1 = ResourceRaidenShogunTexcoord

[TextureOverrideRaidenShogunVertexLimitRaise]
hash = 29bb54cb

[TextureOverrideRaidenShogunIB]
hash = 7a583c12
handling = skip
drawindexed = auto

[TextureOverrideRaidenShogunHead]
hash = 7a583c12
match_first_index = 0
ib = ResourceRaidenShogunHeadIB
ps-t0 = ResourceRaidenShogunHeadDiffuse
ps-t1 = ResourceRaidenShogunHeadLightMap
run = CommandList\global\ORFix\NNFix


[TextureOverrideRaidenShogunBody]
hash = 7a583c12
match_first_index = 17769
ib = ResourceRaidenShogunBodyIB
ps-t0 = ResourceRaidenShogunBodyDiffuse
ps-t1 = ResourceRaidenShogunBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideRaidenShogunDress]
hash = 7a583c12
match_first_index = 52473
ib = ResourceRaidenShogunDressIB
ps-t0 = ResourceRaidenShogunDressDiffuse
ps-t1 = ResourceRaidenShogunDressLightMap
ps-t69 = ResourceRaidenShogunDressTransparencyMap
run = CommandList\TexFx\Transparency.0
run = CommandList\global\ORFix\NNFix

[TextureOverrideRaidenShogunFaceHeadDiffuse]
hash = 20174ee8
ps-t0 = ResourceRaidenShogunFaceHeadDiffuse
run = CommandList\global\ORFix\NNFix

; CommandList -----------------------

; Resources -------------------------

[ResourceRaidenShogunPosition]
type = Buffer
stride = 40
filename = RaidenShogunPosition.buf

[ResourceRaidenShogunBlend]
type = Buffer
stride = 32
filename = RaidenShogunBlend.buf

[ResourceRaidenShogunTexcoord]
type = Buffer
stride = 20
filename = RaidenShogunTexcoord.buf

[ResourceRaidenShogunHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RaidenShogunHead.ib

[ResourceRaidenShogunBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RaidenShogunBody.ib

[ResourceRaidenShogunDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RaidenShogunDress.ib

[ResourceRaidenShogunHeadDiffuse]
filename = RaidenShogunHeadDiffuse.dds

[ResourceRaidenShogunHeadLightMap]
filename = RaidenShogunHeadLightMap.dds

[ResourceRaidenShogunBodyDiffuse]
filename = RaidenShogunBodyDiffuse.dds

[ResourceRaidenShogunBodyLightMap]
filename = RaidenShogunBodyLightMap.dds

[ResourceRaidenShogunDressDiffuse]
filename = RaidenShogunDressDiffuse.dds

[ResourceRaidenShogunDressLightMap]
filename = RaidenShogunDressLightMap.dds

[ResourceRaidenShogunFaceHeadDiffuse]
filename = RaidenShogunFaceHeadDiffuse.dds

[ResourceRaidenShogunDressTransparencyMap]
filename = RaidenShogunDressTransparencyMap.dds

; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord


; --------------- Raiden Boss Fix ---------------
; Raiden Boss fixed by NK#1321 if you used it for fix your Raiden mods pls give credit for "Nhok0169"
; Thank nguen#2011 SilentNightSound#7430 HazrateGolabi#1364 and Albert Gold#2696 for support

[TextureOverrideRaidenShogunRemapBlend]
hash = fe5c0180
vb1 = ResourceRaidenShogunRemapBlend
handling = skip
draw = 22906,0


[ResourceRaidenShogunRemapBlend]
type = Buffer
stride = 32
filename = RaidenShogunRemapBlend.buf


; -----------------------------------------------