; Ayato

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideAyatoPosition]
hash = b473c856
vb0 = ResourceAyatoPosition

[TextureOverrideAyatoBlend]
hash = 19b13b6e
vb1 = ResourceAyatoBlend
handling = skip
draw = 30215,0 

[TextureOverrideAyatoTexcoord]
hash = 2482a5ee
vb1 = ResourceAyatoTexcoord

[TextureOverrideAyatoVertexLimitRaise]
hash = bf198f17

[TextureOverrideAyatoIB]
hash = e59b09d6
;hash = dd4f6309
handling = skip
drawindexed = auto

[TextureOverrideAyatoHead]
hash = e59b09d6
;hash = dd4f6309
match_first_index = 0
ib = ResourceAyatoHeadIB
ps-t0 = ResourceAyatoHeadDiffuse
ps-t1 = ResourceAyatoHeadLightMap

[TextureOverrideAyatoBody]
hash = e59b09d6
;hash = dd4f6309
match_first_index = 29769
ib = ResourceAyatoBodyIB
ps-t0 = ResourceAyatoBodyDiffuse
ps-t1 = ResourceAyatoBodyLightMap

[TextureOverrideAyatoDress]
hash = e59b09d6
;hash = dd4f6309
match_first_index = 66183
ib = ResourceAyatoDressIB
ps-t0 = ResourceAyatoDressDiffuse
ps-t1 = ResourceAyatoDressLightMap

[TextureOverrideAyatoFaceHeadDiffuse]
hash = 6e40e741
ps-t0 = ResourceAyatoFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceAyatoPosition]
type = Buffer
stride = 40
filename = AyatoPosition.buf

[ResourceAyatoBlend]
type = Buffer
stride = 32
filename = AyatoBlend.buf

[ResourceAyatoTexcoord]
type = Buffer
stride = 20
filename = AyatoTexcoord.buf

[ResourceAyatoHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AyatoHead.ib

[ResourceAyatoBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AyatoBody.ib

[ResourceAyatoDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AyatoDress.ib

[ResourceAyatoHeadDiffuse]
filename = AyatoHeadDiffuse.dds

[ResourceAyatoHeadLightMap]
filename = AyatoHeadLightMap.dds

[ResourceAyatoBodyDiffuse]
filename = AyatoBodyDiffuse.dds

[ResourceAyatoBodyLightMap]
filename = AyatoBodyLightMap.dds

[ResourceAyatoDressDiffuse]
filename = AyatoDressDiffuse.dds

[ResourceAyatoDressLightMap]
filename = AyatoDressLightMap.dds

[ResourceAyatoFaceHeadDiffuse]
filename = AyatoFaceHeadDiffuse.dds


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord

; 4.1 Character Fix 
[TextureOverride41FixVertexLimitRaise]
hash = 36fca030
