; Skirk

; Constants -------------------------


; Overrides -------------------------

[TextureOverrideSkirkFrontHairPosition]
hash = 1d025d3b
vb0 = ResourceSkirkFrontHairPosition

[TextureOverrideSkirkFrontHairBlend]
hash = e520d278
handling = skip
vb1 = ResourceSkirkFrontHairBlend
draw = 2443, 0

[TextureOverrideSkirkFrontHairTexcoord]
hash = 6ac3b9bf
vb1 = ResourceSkirkFrontHairTexcoord

[TextureOverrideSkirkFrontHairVertexLimitRaise]
hash = 49393f27
override_vertex_count = 2443
override_byte_stride = 40

[TextureOverrideSkirkBodyPosition]
hash = 9ce8105a
vb0 = ResourceSkirkBodyPosition

[TextureOverrideSkirkBodyBlend]
hash = f7cfc40f
handling = skip
vb1 = ResourceSkirkBodyBlend
draw = 48179, 0

[TextureOverrideSkirkBodyTexcoord]
hash = 0c49941e
vb1 = ResourceSkirkBodyTexcoord

[TextureOverrideSkirkBodyVertexLimitRaise]
hash = 52da0bc7
override_vertex_count = 48179
override_byte_stride = 40

[TextureOverrideSkirkEyesPosition]
hash = 02c3f76e
vb0 = ResourceSkirkEyesPosition

[TextureOverrideSkirkEyesBlend]
hash = 65564c8b
handling = skip
vb1 = ResourceSkirkEyesBlend
draw = 229, 0

[TextureOverrideSkirkEyesTexcoord]
hash = 02a55582
vb1 = ResourceSkirkEyesTexcoord

[TextureOverrideSkirkEyesVertexLimitRaise]
hash = 198acd39
override_vertex_count = 229
override_byte_stride = 40

[TextureOverrideSkirkBackHairPosition]
hash = a788689b
vb0 = ResourceSkirkBackHairPosition

[TextureOverrideSkirkBackHairBlend]
hash = e1de8e8e
handling = skip
vb1 = ResourceSkirkBackHairBlend
draw = 6284, 0

[TextureOverrideSkirkBackHairTexcoord]
hash = 5979231d
vb1 = ResourceSkirkBackHairTexcoord

[TextureOverrideSkirkBackHairVertexLimitRaise]
hash = b8b82723
override_vertex_count = 6284
override_byte_stride = 40

[TextureOverrideSkirkFrontHairIB]
hash = 74811ddf
handling = skip

[TextureOverrideSkirkFrontHairA]
hash = 74811ddf
match_first_index = 0
ib = ResourceSkirkFrontHairAIB
ps-t0 = ResourceSkirkFrontHairANormalMap
ps-t1 = ResourceSkirkFrontHairADiffuse
ps-t2 = ResourceSkirkFrontHairALightMap
run = CommandList\global\ORFix\ORFix
; SkirkFrontHairA (2443)
drawindexed = 8334, 0, 0

[TextureOverrideSkirkBodyIB]
hash = 1fbe8217
handling = skip

[TextureOverrideSkirkBodyA]
hash = 1fbe8217
match_first_index = 0
ib = ResourceSkirkBodyAIB
ps-t0 = ResourceSkirkBodyADiffuse
ps-t1 = ResourceSkirkBodyALightMap
; SkirkBodyA (29438)
drawindexed = 164100, 0, 0
; SkirkBodyA
; 3 (18741)
drawindexed = 77844, 164100, 0

[TextureOverrideSkirkEyesIB]
hash = a831e5b5
handling = skip

[TextureOverrideSkirkEyesA]
hash = a831e5b5
match_first_index = 0
ib = ResourceSkirkEyesAIB
ps-t0 = ResourceSkirkEyesADiffuse
ps-t1 = ResourceSkirkEyesALightMap
; SkirkEyesA (229)
drawindexed = 672, 0, 0

[TextureOverrideSkirkSkirtIB]
hash = 056da8f3
handling = skip

[TextureOverrideSkirkBackHairIB]
hash = dafe18b6
handling = skip

[TextureOverrideSkirkBackHairA]
hash = dafe18b6
match_first_index = 0
ib = ResourceSkirkBackHairAIB
ps-t0 = ResourceSkirkBackHairANormalMap
ps-t1 = ResourceSkirkBackHairADiffuse
ps-t2 = ResourceSkirkBackHairALightMap
run = CommandList\global\ORFix\ORFix
; SkirkBackHairA (1934)
drawindexed = 6138, 0, 0

[TextureOverrideSkirkBackHairB]
hash = dafe18b6
match_first_index = 13650
ib = ResourceSkirkBackHairBIB
ps-t0 = ResourceSkirkBackHairBDiffuse
ps-t1 = ResourceSkirkBackHairBLightMap
ps-t2 = ResourceSkirkBackHairBStockingMap
; SkirkBackHairB (2175)
drawindexed = 9666, 0, 0
; SkirkBackHairB
; 2 (2175)
drawindexed = 9666, 9666, 0


; CommandList -----------------------


; Resources -------------------------

[ResourceSkirkFrontHairPosition]
type = Buffer
stride = 40
filename = SkirkFrontHairPosition.buf

[ResourceSkirkFrontHairBlend]
type = Buffer
stride = 32
filename = SkirkFrontHairBlend.buf

[ResourceSkirkFrontHairTexcoord]
type = Buffer
stride = 12
filename = SkirkFrontHairTexcoord.buf

[ResourceSkirkFrontHairAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SkirkFrontHairA.ib

[ResourceSkirkBodyPosition]
type = Buffer
stride = 40
filename = SkirkBodyPosition.buf

[ResourceSkirkBodyBlend]
type = Buffer
stride = 32
filename = SkirkBodyBlend.buf

[ResourceSkirkBodyTexcoord]
type = Buffer
stride = 20
filename = SkirkBodyTexcoord.buf

[ResourceSkirkBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SkirkBodyA.ib

[ResourceSkirkEyesPosition]
type = Buffer
stride = 40
filename = SkirkEyesPosition.buf

[ResourceSkirkEyesBlend]
type = Buffer
stride = 32
filename = SkirkEyesBlend.buf

[ResourceSkirkEyesTexcoord]
type = Buffer
stride = 12
filename = SkirkEyesTexcoord.buf

[ResourceSkirkEyesAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SkirkEyesA.ib

[ResourceSkirkBackHairPosition]
type = Buffer
stride = 40
filename = SkirkBackHairPosition.buf

[ResourceSkirkBackHairBlend]
type = Buffer
stride = 32
filename = SkirkBackHairBlend.buf

[ResourceSkirkBackHairTexcoord]
type = Buffer
stride = 20
filename = SkirkBackHairTexcoord.buf

[ResourceSkirkBackHairAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SkirkBackHairA.ib

[ResourceSkirkBackHairBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SkirkBackHairB.ib

[ResourceSkirkFrontHairANormalMap]
filename = SkirkFrontHairANormalMap.dds

[ResourceSkirkFrontHairADiffuse]
filename = SkirkFrontHairADiffuse.dds

[ResourceSkirkFrontHairALightMap]
filename = SkirkFrontHairALightMap.dds

[ResourceSkirkBodyADiffuse]
filename = SkirkBodyADiffuse.dds

[ResourceSkirkBodyALightMap]
filename = SkirkBodyALightMap.dds

[ResourceSkirkEyesADiffuse]
filename = SkirkEyesADiffuse.dds

[ResourceSkirkEyesALightMap]
filename = SkirkEyesALightMap.dds

[ResourceSkirkSkirtADiffuse]
filename = SkirkSkirtADiffuse.dds

[ResourceSkirkSkirtALightMap]
filename = SkirkSkirtALightMap.dds

[ResourceSkirkBackHairANormalMap]
filename = SkirkBackHairANormalMap.dds

[ResourceSkirkBackHairADiffuse]
filename = SkirkBackHairADiffuse.dds

[ResourceSkirkBackHairALightMap]
filename = SkirkBackHairALightMap.dds

[ResourceSkirkBackHairBDiffuse]
filename = SkirkBackHairBDiffuse.dds

[ResourceSkirkBackHairBLightMap]
filename = SkirkBackHairBLightMap.dds

[ResourceSkirkBackHairBStockingMap]
filename = SkirkBackHairBStockingMap.dds


; .ini generated by XXMI (XX-Model-Importer) v1.5.4
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues
