; hutao

; Constants -------------------------

; Overrides -------------------------

[TextureOverridehutaoPosition]
hash = dd16576c
vb0 = ResourcehutaoPosition

[TextureOverridehutaoBlend]
hash = 153dba3f
vb1 = ResourcehutaoBlend
handling = skip
draw = 67041,0 

[TextureOverridehutaoTexcoord]
hash = 51afdfcf
vb1 = ResourcehutaoTexcoord

[TextureOverridehutaoVertexLimitRaise]
hash = e9d17db6

[TextureOverridehutaoIB]
hash = 3de1efe2
handling = skip
drawindexed = auto

[TextureOverridehutaoHead]
hash = 3de1efe2
match_first_index = 0
ib = ResourcehutaoHeadIB
ps-t0 = ResourcehutaoHeadDiffuse
ps-t1 = ResourcehutaoHeadLightMap

[TextureOverridehutaoBody]
hash = 3de1efe2
match_first_index = 16509
ib = ResourcehutaoBodyIB
ps-t0 = ResourcehutaoBodyDiffuse
ps-t1 = ResourcehutaoBodyLightMap

; CommandList -----------------------

; Resources -------------------------

[ResourcehutaoPosition]
type = Buffer
stride = 40
filename = hutaoPosition.buf

[ResourcehutaoBlend]
type = Buffer
stride = 32
filename = hutaoBlend.buf

[ResourcehutaoTexcoord]
type = Buffer
stride = 12
filename = hutaoTexcoord.buf

[ResourcehutaoHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = hutaoHead.ib

[ResourcehutaoBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = hutaoBody.ib

[ResourcehutaoHeadDiffuse]
filename = hutaoHeadDiffuse.dds

[ResourcehutaoHeadLightMap]
filename = hutaoHeadLightMap.dds

[ResourcehutaoBodyDiffuse]
filename = hutaoBodyDiffuse.dds

[ResourcehutaoBodyLightMap]
filename = hutaoBodyLightMap.dds


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord