; Kirara

; Constants -------------------------

[Constants]
global $active = 0
global $creditinfo = 0

[Present]
post $active = 0
run = CommandListCreditInfo

; Overrides -------------------------

[TextureOverrideKiraraPosition]
hash = b57d7fe2
vb0 = ResourceKiraraPosition
$active = 1

[TextureOverrideKiraraBlend]
hash = 01d54938
vb1 = ResourceKiraraBlend
handling = skip
draw = 81876, 0 

[TextureOverrideKiraraTexcoord]
hash = 33b3d6e5
vb1 = ResourceKiraraTexcoord

[TextureOverrideKiraraVertexLimitRaise]
hash = 6fb396da

[TextureOverrideKiraraIB]
hash = f6e9af7d
handling = skip


[TextureOverrideKiraraHead]
hash = f6e9af7d
match_first_index = 0
ib = ResourceKiraraHeadIB
ps-t0 = ResourceKiraraHeadNormalMap
ps-t1 = ResourceKiraraHeadDiffuse
ps-t2 = ResourceKiraraHeadLightMap
run = CommandList\global\ORFix\ORFix
if $basebody == 1
  drawindexed = 18786, 0, 0
endif
if $shirt == 1
  drawindexed = 6, 18786, 0
endif
if $shorts == 1
  drawindexed = 6, 18792, 0
endif
if $bra == 1
  drawindexed = 6, 18798, 0
endif
if $catears == 1
  drawindexed = 1566, 18804, 0
endif
if $headwear == 1
  drawindexed = 3468, 20370, 0
endif
if $mask == 1
  drawindexed = 6, 23838, 0
endif
if $catbody == 1
  drawindexed = 18786, 23844, 0
endif
if $panty == 1
  drawindexed = 6, 42630, 0
endif


[TextureOverrideKiraraBody]
hash = f6e9af7d
match_first_index = 37128
ib = ResourceKiraraBodyIB
ps-t0 = ResourceKiraraBodyNormalMap
ps-t1 = ResourceKiraraBodyDiffuse
ps-t2 = ResourceKiraraBodyLightMap
run = CommandList\global\ORFix\ORFix
if $basebody == 1
  drawindexed = 138138, 0, 0
endif
if $shirt == 1
  drawindexed = 6, 138138, 0
endif
if $shorts == 1
  drawindexed = 6, 138144, 0
endif
if $bra == 1
  drawindexed = 6, 138150, 0
endif
if $catears == 1
  drawindexed = 6, 138156, 0
endif
if $headwear == 1
  drawindexed = 6, 138162, 0
endif
if $mask == 1
  drawindexed = 6, 138168, 0
endif
if $catbody == 1
  drawindexed = 121734, 138174, 0
endif
if $panty == 1
  drawindexed = 6, 259908, 0
endif


[TextureOverrideKiraraDress]
hash = f6e9af7d
match_first_index = 75234
ib = ResourceKiraraDressIB
ps-t0 = ResourceKiraraDressNormalMap
ps-t1 = ResourceKiraraDressDiffuse
ps-t2 = ResourceKiraraDressLightMap
run = CommandList\global\ORFix\ORFix
if $basebody == 1
  drawindexed = 16314, 0, 0
endif
if $shirt == 1
  drawindexed = 26190, 16314, 0
endif
if $shorts == 1
  drawindexed = 11238, 42504, 0
endif
if $bra == 1
  drawindexed = 6699, 53742, 0
endif
if $catears == 1
  drawindexed = 6, 60441, 0
endif
if $headwear == 1
  drawindexed = 6, 60447, 0
endif
if $mask == 1
  drawindexed = 942, 60453, 0
endif
if $catbody == 1
  drawindexed = 20880, 61395, 0
endif
if $panty == 1
  drawindexed = 14154, 82275, 0
endif


[TextureOverrideKiraraFaceHeadNormalMap]
hash = 6eb20522
ps-t0 = ResourceKiraraFaceHeadNormalMap


; CommandList -----------------------

[CommandListCreditInfo]
if $creditinfo == 0 && $active == 1
	pre Resource\ShaderFixes\help.ini\Notification = ResourceCreditInfo
	pre run = CustomShader\ShaderFixes\help.ini\FormatText
	pre $\ShaderFixes\help.ini\notification_timeout = time + 5.0
	$creditinfo = 1
endif

; Resources -------------------------

[ResourceKiraraPosition]
type = Buffer
stride = 40
filename = KiraraPosition.buf

[ResourceKiraraBlend]
type = Buffer
stride = 32
filename = KiraraBlend.buf

[ResourceKiraraTexcoord]
type = Buffer
stride = 20
filename = KiraraTexcoord.buf

[ResourceKiraraHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KiraraHead.ib

[ResourceKiraraBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KiraraBody.ib

[ResourceKiraraDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KiraraDress.ib

[ResourceKiraraHeadNormalMap]
filename = KiraraHeadNormalMap.dds

[ResourceKiraraHeadDiffuse]
filename = KiraraHeadDiffuse.dds

[ResourceKiraraHeadLightMap]
filename = KiraraHeadLightMap.dds

[ResourceKiraraBodyNormalMap]
filename = KiraraBodyNormalMap.dds

[ResourceKiraraBodyDiffuse]
filename = KiraraBodyDiffuse.dds

[ResourceKiraraBodyLightMap]
filename = KiraraBodyLightMap.dds

[ResourceKiraraDressNormalMap]
filename = KiraraDressNormalMap.dds

[ResourceKiraraDressDiffuse]
filename = KiraraDressDiffuse.dds

[ResourceKiraraDressLightMap]
filename = KiraraDressLightMap.dds

[ResourceKiraraFaceHeadNormalMap]
filename = KiraraFaceHeadNormalMap.dds

[ResourceCreditInfo]
type = Buffer
data = "Use H for info"


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord
[Constants]
global persist $basebody = 1
global persist $shirt = 1
global persist $shorts = 1
global persist $bra = 1
global persist $catears = 1
global persist $headwear = 0
global persist $mask = 0
global persist $catbody = 0
global persist $panty = 1
[KeySwap0]
key = 5
condition = $active == 1
type = cycle
$basebody = 0,1
$catbody = 1,0
[KeySwap1]
key = 6
condition = $active == 1
type = cycle
$shirt = 0,1,1,0
$bra = 0,0,1,1
[KeySwap2]
key = 7
condition = $active == 1
type = cycle
$shorts = 0,1,0,1
$panty = 0,0,1,1
[KeySwap4]
key = 8
condition = $active == 1
type = cycle
$catears = 0,1,0,1
$headwear = 0,1,1,0
[KeySwap6]
key = 9
condition = $active == 1
type = cycle
$mask = 0,1

[KeyNude]
key = N
condition = $active == 1
type = cycle
$catbody = 1,1,1
$basebody = 0,0,0
$bra = 0,1,1
$panty = 0,1,1
$shirt = 0,1,0
$shorts = 0,1,0


